####################################################################
## This file is automatically generated
## Do not edit manually
####################################################################

from .reactopyacolabwidget import ReactopyaColabWidget
from .reactopyaelectronwidget import ReactopyaElectronWidget
from .init import _get_init_info

from .widgets import PlaceField as PlaceFieldOrig
from .widgets import Accordion as AccordionOrig
from .widgets import Autocorrelograms as AutocorrelogramsOrig
from .widgets import NWBView as NWBViewOrig
from .widgets import VBox as VBoxOrig
from .widgets import NWBBrowser as NWBBrowserOrig
from .widgets import HBox as HBoxOrig
from .widgets import ElectrodeGeometry as ElectrodeGeometryOrig
from .widgets import TimeseriesView as TimeseriesViewOrig
from .widgets import SpikeForestAnalysis as SpikeForestAnalysisOrig
from .widgets import Tabs as TabsOrig



class PlaceField:
    """Jupyter widget for PlaceField"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = PlaceFieldOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='PlaceField',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='PlaceField',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class Accordion:
    """Jupyter widget for Accordion"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = AccordionOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='Accordion',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='Accordion',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class Autocorrelograms:
    """Jupyter widget for Autocorrelograms"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = AutocorrelogramsOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='Autocorrelograms',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='Autocorrelograms',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class NWBView:
    """Jupyter widget for NWBView"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = NWBViewOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='NWBView',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='NWBView',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class VBox:
    """Jupyter widget for VBox"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = VBoxOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='VBox',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='VBox',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class NWBBrowser:
    """Jupyter widget for NWBBrowser"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = NWBBrowserOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='NWBBrowser',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='NWBBrowser',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class HBox:
    """Jupyter widget for HBox"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = HBoxOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='HBox',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='HBox',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class ElectrodeGeometry:
    """Jupyter widget for ElectrodeGeometry"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = ElectrodeGeometryOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='ElectrodeGeometry',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='ElectrodeGeometry',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class TimeseriesView:
    """Jupyter widget for TimeseriesView"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = TimeseriesViewOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='TimeseriesView',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='TimeseriesView',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class SpikeForestAnalysis:
    """Jupyter widget for SpikeForestAnalysis"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = SpikeForestAnalysisOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='SpikeForestAnalysis',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='SpikeForestAnalysis',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()

class Tabs:
    """Jupyter widget for Tabs"""

    def __init__(self, *args, **kwargs):
        super().__init__()
        self._props = dict(**kwargs)
        self._children = list(args)
        self._component = TabsOrig()
        self._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, []))
        self._connect_children(self._children, [])
        self._reactopya_widget = None
        self._component.init_jupyter()
    
    def _connect_children(self, children, child_indices):
        for i, ch in enumerate(children):
            self._connect_child(ch, child_indices + [i])
            self._connect_children(ch._children, child_indices + [i])
    
    def _connect_child(self, child, child_indices):
        child._component.on_python_state_changed(lambda state: self._handle_python_state_changed(state, child_indices))
    
    def _handle_python_state_changed(self, state, child_indices):
        if self._reactopya_widget:
            self._reactopya_widget.set_python_state(state, child_indices)

    def _handle_javascript_state_changed(self, state, child_indices):
        ptr = self
        for ind in child_indices:
            ptr = ptr._children[ind]
        ptr._component._handle_javascript_state_changed(state)

    def _serialize(self):
        return dict(
            project_name='ephys_viz',
            type='Tabs',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )

    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        init_info = _get_init_info()
        if init_info['mode'] == 'jupyter':
            from reactopya_jup import ReactopyaWidget as ReactopyaJupyterWidget
            RW = ReactopyaJupyterWidget
        elif init_info['mode'] == 'colab':
            RW = ReactopyaColabWidget
        elif init_info['mode'] == 'electron':
            RW = ReactopyaElectronWidget
        self._reactopya_widget = RW(
            project_name='ephys_viz',
            type='Tabs',
            children=[
                ch._serialize()
                for ch in self._children
            ],
            props=self._props
        )
        if init_info['mode'] == 'colab':
            self._reactopya_widget._set_bundle_js(init_info['bundle_js'], store_bundle_in_notebook=init_info['store_bundle_in_notebook'])
        elif init_info['mode'] == 'electron':
            self._reactopya_widget._set_bundle_fname(init_info['bundle_fname'])
            self._reactopya_widget._set_electron_src(init_info['electron_src'])
        self._reactopya_widget.on_javascript_state_changed(self._handle_javascript_state_changed)

        self._reactopya_widget.show()
