
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-27T20:58:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "83ebb2739a4e91130848506cfc16b4a86c04ea21",
 "version": "2.3.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
