# travis-ci integration for the kll compiler

dist: xenial

os:
  - linux

language:
  - python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

# Exclusions
matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

# System setup
install:
  # Info about OS
  - uname -a

  # Prepare pipenv
  # XXX (pip and pipenv pinning will have to be removed to support Python 3.8)
  - pip install --upgrade pip==18.0
  - pip install pipenv==2018.10.9 flit pip==18.0
  - pipenv install -d

# Run test script(s)
script:
  - pipenv run pytest -s
  - pipenv run flit build

