
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-19T14:08:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ece432dff8772b7318586ffc2e8fb1f5d41ea35",
 "version": "5.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
