
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-26T12:20:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "44717ebf306f0dbbe178c4b4b47ed3f15584ee09",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
