[tool.poetry]
name = "red-connector-http"
version = "1.0"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-http"
homepage = "https://www.curious-containers.cc/"
description = "RED Connector HTTP is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
requests = "^2.18"
jsonschema = "^3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-http = 'red_connector_http.http.main:main'
red-connector-http-json = 'red_connector_http.http_json.main:main'
red-connector-http-archive = 'red_connector_http.http_archive.main:main'
