[tool.poetry]
name = "snakesist"
version = "0.1.0-beta1"
description = "A Python database connector for eXist-db"
authors = ["Theodor Costea <theo.costea@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
lxml = "^4.3"
delb = "^0.1.0"
sphinx_rtd_theme = "^0.4.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
requests_mock = "^1.6"
sphinx = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
