# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-08-26T02:17:30.230966'

__version__ = '2019.8.5'
__sha__ = '0d07537ac6cbb91c9dfa52609ae3f33abec666c9'
__revision__ = '0d07537ac6cbb91c9dfa52609ae3f33abec666c9'
