"""Autogenerated file: DO NOT EDIT!"""
import typing
from dazzler.system import Component, Aspect, UNDEFINED


class Pager(Component):
    """
    Paging for dazzler apps.

    """
    _aspect_keys = []
    _children = []
    id = Aspect()
    style = Aspect()
    className = Aspect()
    page_style = Aspect()
    page_className = Aspect()
    total_items = Aspect()
    items_per_page = Aspect(default=10)
    pages_displayed = Aspect(default=10)
    pages = Aspect()
    current_page = Aspect(default=1)
    total_pages = Aspect()
    start_offset = Aspect()
    end_offset = Aspect()

    def __init__(
            self,
            id: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            className: typing.Optional[str] = UNDEFINED,
            page_style: typing.Optional[typing.Dict] = UNDEFINED,
            page_className: typing.Optional[str] = UNDEFINED,
            total_items: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            items_per_page: typing.Optional[typing.Union[float, int]] = 10,
            pages_displayed: typing.Optional[typing.Union[float, int]] = 10,
            pages: typing.Optional[typing.List] = UNDEFINED,
            current_page: typing.Optional[typing.Union[float, int]] = 1,
            total_pages: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            start_offset: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            end_offset: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            identity: str = None
    ):
        """
        :param id:
        :param style:
        :param className:
        :param page_style: Style for the page numbers.
        :param page_className: CSS class for the page numbers.
        :param total_items: The total items in the set.
        :param items_per_page: The number of items a page contains. (default=10)
        :param pages_displayed: The number of pages displayed by the pager.
            (default=10)
        :param pages: Read only, the currently displayed pages numbers.
        :param current_page: The current selected page. (default=1)
        :param total_pages: Set by total_items / items_per_page
        :param start_offset: The starting index of the current page Can be used to
            slice data eg: data[start_offset: end_offset]
        :param end_offset: The end index of the current page.
        """
        Component.__init__(self, locals(), identity)
