
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-19T14:42:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d472dafdf8ffc0481071e1b1aeb91983857b13f",
 "version": "0.68.0.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
