
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-27T13:10:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e473f5c2c972f43f0bae7dfd9459b1713ecd1ec5",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
