#
#   This file is used to configure the continuous integration for vulndb/data
#
#   As a user you don't need to understand this file.
#
version: 2

jobs:
  build:

    docker:
      - image: circleci/python:2.7.14

    steps:
      - checkout

      - run:
          command: |
            pip install --upgrade pip
            pip install --user --upgrade -r vulndb/requirements-dev.txt
            pip --version
            pip freeze

      - run:
          command: |
            /home/circleci/.local/bin/nosetests -s -v vulndb/
            /home/circleci/.local/bin/pylint --msg-template='{msg_id}:{line:3d},{column}: {obj}: {msg}' -E vulndb/ setup.py
