dir_name: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/nwb_files
main_window_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures
yaml_analysis_args_dir_name: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/yaml_cicada_args
