################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util

from jpype.types import *
from typing import Union

from typing import overload

class VMSupport:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	@staticmethod
	def isClassPathAttributePresent(arg0: javawrappers.java.lang.String, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def serializePropertiesToByteArray() -> JArray(JByte, 1): ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	@staticmethod
	def serializeAgentPropertiesToByteArray() -> JArray(JByte, 1): ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def getVMTemporaryDirectory() -> javawrappers.java.lang.String: ...
	@staticmethod
	def getAgentProperties() -> javawrappers.java.util.Properties: ...
	def notify(self, ) -> None: ...


