tier1:
  - tracks

tier2: 
  - speech
  - music
  - mixed
  - effects
  - filler
  - simple
  - moderate
  - complex
  - mono
  - stereo
  - surround
  - surround-2.1
  - surround-3.0
  - surround-4.0
  - surround-5.1
  - surround-7.1
  - surround-10.2
  - surround-11.1
  - surround-22.2
  - surround-ambisonics
  - surround-binaural
  - surround-panambio

values:
  type:
    - speech
    - music
    - mixed
    - effects
    - filler

  complexity:
    - simple
    - moderate
    - complex

  channels:
    - mono
    - stereo
    - surround
    - surround-2.1
    - surround-3.0
    - surround-4.0
    - surround-5.1
    - surround-7.1
    - surround-10.2
    - surround-11.1
    - surround-22.2
    - surround-ambisonics
    - surround-binaural
    - surround-panambio

defaults:
  type: music
  complexity: moderate
  channels: stereo

order: [type, complexity, channels]
