[tool.poetry]
name = "django-base-publications"
version = "0.0.6"
description = ""
authors = ["Дмитрий <acrius@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.5"
ipython = "^7.7"
django = "^1.11 || ^2.0"
django-autoslug = "^1.9"
funcy = "^1.13"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
