# -*- coding: utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=utf8
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

__VERSION__ = "0.1.0"
