[tool.poetry]
name = "tulips"
version = "1.4.5"
description = "Wrapper around kubernetes-clients/python"
authors = ["Janez Troha <dz0ny@ubuntu.si>"]
license = "MIT"
readme = 'README.md'

repository = "https://github.com/dz0ny/tulips"
homepage = "https://github.com/dz0ny/tulips"

[tool.poetry.dependencies]
python = "^3.6"
kubernetes = "^9.0.0"
click = "^6.7"
structlog = "^18.1"
passlib = "^1.7"
"ruamel.yaml" = "^0.15.89"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
mypy = "^0.610.0"
isort = "^4.3"
flake8 = "^3.5"
flake8-bugbear = "^18.2"
pylint = "^1.9"
black = "^18.4-alpha.0"
codecov = "^2.0"
pytest-cov = "^2.5"
pytest-mock = "^1.10"

[tool.black]
line-length = 79
py36 = true
include = '\.pyi?$'
