dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: sWg7JBkDIM8+S4h6SQhNJ7rRX5BjrtGN+sSIX+O6QwMD+/ZKfKI2SKWtH45C6DOpUHZft40Pr1GY4PTqopks+PxFUr7Z/j/FteaMGYLGoSaYtvI7A5xgzD6dh5Myj8t+6rx+2IflztU72Xs7FckZQP1NngGLqbnG5FmOEjPaK2on+zfxYr6ue0zoghAKVzHpw4kFx6snMnjw/Zuky/a8R0rgD7sQ/lOGaVRZGq0sk7cMddifR+hHctKsnE5MDdkadcsAp4E65xPQfLJWjSuQm8GCOMxXy2Uxu2QaPak5ySRjqMKXAweZAG6ERIq5j16Hr3NtfAObrIkYICp7qabbbTV6WsY+Y4E275hRmCLAc+bN0z5xY5SMg40FFq38t1CCvdAmkLizmJnD6cxziPEPt7o5jekTkijLdFPDPcEuhq2QIM0JMTS/EwUbN9BuCKs7VRO9TQ0JPcSaFL2Xh8HTtsV3qrfOxvoReTLHGGZlz7A1W2NWfzI2tVGEcbh0sBDAEauutK6+vOQO3hvI/0Vq/Lek5yloJ2shksfrwLvWRZJDlSi5bSmQTLzP0BfPFwZc1D3D7KJOtHe3IqY5KCwbYGAn/+j/MNitULw+F/nspYYYANd37gFKWuslpIQgUfaLLU8gM70+6Zj+E/fiOzl18FVK8KNhxTBIsUMyIpoZ73Y=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_lis3dh.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-lis3dh --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
