################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.nio.file.spi
import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.java.net
import javawrappers.java.io
import javawrappers.java.util.concurrent
import javawrappers.java.nio.channels
import javawrappers.sun.nio.fs
import javawrappers.java.nio.file
import javawrappers.java.nio.file.attribute

from jpype.types import *
from typing import Union

from typing import overload

class ExtendedOptions:
	def __init__(self, ): ...
	class InternalOption:
		def getClass(self, ) -> javawrappers.java.lang.Class: ...
		@overload
		def wait(self, arg0: Union[long, JLong], ) -> None: ...
		@overload
		def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
		@overload
		def wait(self, ) -> None: ...
		def hashCode(self, ) -> Union[int, JInt]: ...
		def notifyAll(self, ) -> None: ...
		def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def parameter(self, ) -> javawrappers.java.lang.Object: ...
		def toString(self, ) -> javawrappers.java.lang.String: ...
		def matches(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def notify(self, ) -> None: ...
		@overload
		def register(self, arg0: javawrappers.java.nio.file.WatchEvent.Modifier, arg1: javawrappers.java.lang.Object, ) -> None: ...
		@overload
		def register(self, arg0: javawrappers.java.nio.file.WatchEvent.Modifier, ) -> None: ...
		@overload
		def register(self, arg0: javawrappers.java.nio.file.CopyOption, ) -> None: ...
		@overload
		def register(self, arg0: javawrappers.java.nio.file.OpenOption, ) -> None: ...


	class Wrapper:
		def getClass(self, ) -> javawrappers.java.lang.Class: ...
		@overload
		def wait(self, arg0: Union[long, JLong], ) -> None: ...
		@overload
		def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
		@overload
		def wait(self, ) -> None: ...
		def hashCode(self, ) -> Union[int, JInt]: ...
		def notifyAll(self, ) -> None: ...
		def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def toString(self, ) -> javawrappers.java.lang.String: ...
		def notify(self, ) -> None: ...


	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def parameter(self, ) -> javawrappers.java.lang.Object: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def matches(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def notify(self, ) -> None: ...
	@overload
	def register(self, arg0: javawrappers.java.nio.file.WatchEvent.Modifier, arg1: javawrappers.java.lang.Object, ) -> None: ...
	@overload
	def register(self, arg0: javawrappers.java.nio.file.WatchEvent.Modifier, ) -> None: ...
	@overload
	def register(self, arg0: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	@overload
	def register(self, arg0: javawrappers.java.nio.file.OpenOption, ) -> None: ...


class DefaultFileTypeDetector:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def create() -> javawrappers.java.nio.file.spi.FileTypeDetector: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def notify(self, ) -> None: ...


class BasicFileAttributesHolder:
	def get(self, ) -> javawrappers.java.nio.file.attribute.BasicFileAttributes: ...
	def invalidate(self, ) -> None: ...


class AbstractFileSystemProvider:
	def isSameFile(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newByteChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.SeekableByteChannel: ...
	def getFileStore(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.FileStore: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def newAsynchronousFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, arg2: javawrappers.java.util.concurrent.ExecutorService, *arg3: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.AsynchronousFileChannel: ...
	def getFileAttributeView(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.FileAttributeView: ...
	def notifyAll(self, ) -> None: ...
	def createSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	@staticmethod
	def installedProviders() -> javawrappers.java.util.List: ...
	def delete(self, arg0: javawrappers.java.nio.file.Path, ) -> None: ...
	def notify(self, ) -> None: ...
	def createLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> None: ...
	def setAttribute(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.Object, *arg3: javawrappers.java.nio.file.LinkOption, ) -> None: ...
	def newInputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.InputStream: ...
	def newFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.FileChannel: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def newOutputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.OutputStream: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.util.Map: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.BasicFileAttributes: ...
	def getPath(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.Path: ...
	def createDirectory(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	def copy(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def move(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def getScheme(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.net.URI, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	def deleteIfExists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def isRegularFile(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newDirectoryStream(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.DirectoryStream.Filter, ) -> javawrappers.java.nio.file.DirectoryStream: ...
	def getFileSystem(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.FileSystem: ...
	def checkAccess(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.AccessMode, ) -> None: ...
	def readSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.Path: ...
	def isHidden(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def exists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def isDirectory(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...


class DefaultFileSystemProvider:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def create() -> javawrappers.java.nio.file.spi.FileSystemProvider: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def notify(self, ) -> None: ...


class UnixFileSystemProvider:
	def __init__(self, ): ...
	def isSameFile(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newByteChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.SeekableByteChannel: ...
	def getFileStore(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.FileStore: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def newAsynchronousFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, arg2: javawrappers.java.util.concurrent.ExecutorService, *arg3: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.AsynchronousFileChannel: ...
	def getFileAttributeView(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.FileAttributeView: ...
	def notifyAll(self, ) -> None: ...
	def createSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	@staticmethod
	def installedProviders() -> javawrappers.java.util.List: ...
	def delete(self, arg0: javawrappers.java.nio.file.Path, ) -> None: ...
	def notify(self, ) -> None: ...
	def createLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> None: ...
	def setAttribute(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.Object, *arg3: javawrappers.java.nio.file.LinkOption, ) -> None: ...
	def newInputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.InputStream: ...
	def newFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.FileChannel: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def newOutputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.OutputStream: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.BasicFileAttributes: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.util.Map: ...
	def getPath(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.Path: ...
	def createDirectory(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	def copy(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def move(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def getScheme(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.net.URI, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	def deleteIfExists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def isRegularFile(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newDirectoryStream(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.DirectoryStream.Filter, ) -> javawrappers.java.nio.file.DirectoryStream: ...
	def getFileSystem(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.FileSystem: ...
	def checkAccess(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.AccessMode, ) -> None: ...
	def readSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.Path: ...
	def isHidden(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def exists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def isDirectory(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...


class Globs:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def notify(self, ) -> None: ...


class LinuxFileSystemProvider:
	def __init__(self, ): ...
	def isSameFile(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newByteChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.SeekableByteChannel: ...
	def getFileStore(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.FileStore: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def newAsynchronousFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, arg2: javawrappers.java.util.concurrent.ExecutorService, *arg3: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.AsynchronousFileChannel: ...
	@overload
	def getFileAttributeView(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.FileAttributeView: ...
	@overload
	def getFileAttributeView(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.sun.nio.fs.DynamicFileAttributeView: ...
	def notifyAll(self, ) -> None: ...
	def createSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	@staticmethod
	def installedProviders() -> javawrappers.java.util.List: ...
	def delete(self, arg0: javawrappers.java.nio.file.Path, ) -> None: ...
	def notify(self, ) -> None: ...
	def createLink(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, ) -> None: ...
	def setAttribute(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.Object, *arg3: javawrappers.java.nio.file.LinkOption, ) -> None: ...
	def newInputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.InputStream: ...
	def newFileChannel(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Set, *arg2: javawrappers.java.nio.file.attribute.FileAttribute, ) -> javawrappers.java.nio.channels.FileChannel: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def newOutputStream(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.OpenOption, ) -> javawrappers.java.io.OutputStream: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.Class, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.nio.file.attribute.BasicFileAttributes: ...
	@overload
	def readAttributes(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.lang.String, *arg2: javawrappers.java.nio.file.LinkOption, ) -> javawrappers.java.util.Map: ...
	def getPath(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.Path: ...
	def createDirectory(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.attribute.FileAttribute, ) -> None: ...
	def copy(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def move(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.Path, *arg2: javawrappers.java.nio.file.CopyOption, ) -> None: ...
	def getScheme(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.net.URI, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	@overload
	def newFileSystem(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.util.Map, ) -> javawrappers.java.nio.file.FileSystem: ...
	def deleteIfExists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def isRegularFile(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def newDirectoryStream(self, arg0: javawrappers.java.nio.file.Path, arg1: javawrappers.java.nio.file.DirectoryStream.Filter, ) -> javawrappers.java.nio.file.DirectoryStream: ...
	def getFileSystem(self, arg0: javawrappers.java.net.URI, ) -> javawrappers.java.nio.file.FileSystem: ...
	def checkAccess(self, arg0: javawrappers.java.nio.file.Path, *arg1: javawrappers.java.nio.file.AccessMode, ) -> None: ...
	def readSymbolicLink(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.nio.file.Path: ...
	def isHidden(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def exists(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def isDirectory(self, arg0: javawrappers.java.nio.file.Path, ) -> Union[int, JBoolean]: ...


class AbstractFileTypeDetector:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def probeContentType(self, arg0: javawrappers.java.nio.file.Path, ) -> javawrappers.java.lang.String: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def notify(self, ) -> None: ...


