site_name: preconvert
theme:
    name: 'material'
    palette:
      primary: 'green'
      accent: 'lightgreen'
    logo: 'art/logo.png'
    favicon: 'art/logo.png'

repo_name: timothycrosley/preconvert
repo_url: https://github.com/timothycrosley/preconvert
nav:
    - preconvert: index.md
    - Changelog: CHANGELOG.md
    - Reference:
        - Preconvert: 'preconvert/index.md'
        - Convert: 'preconvert/convert.md'
        - Converters: 'preconvert/converters.md'
        - Exceptions: 'preconvert/exceptions.md'
        - Register: 'preconvert/register.md'
        - Output: 'preconvert/output/index.md'
        - JSON: 'preconvert/output/json.md'
        - SimpleJSON: 'preconvert/output/simplejson.md'
        - MsgPack: 'preconvert/output/msgpack.md'
        - BSON: 'preconvert/output/bson.md'
    - Contributing:
        - 'Contributing Guide': 'CONTRIBUTING.md'
        - 'Coding Standard': 'CODING_STANDARD.md'
        - 'Code of Conduct': 'CODE_OF_CONDUCT.md'
        - 'Acknowledgements': 'ACKNOWLEDGEMENTS.md'

markdown_extensions:
  - admonition
  - codehilite
  - extra
