# Autogenerated by Astropy-affiliated package beast's setup.py on 2019-09-05 20:44:54 UTC
from __future__ import unicode_literals
import datetime

version = "1.3.2"
githash = "48588188da7f7cf5faf6b11040799480a36d1bd5"


major = 1
minor = 3
bugfix = 2

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 9, 5, 20, 44, 54)
debug = False

astropy_helpers_version = "3.2.1"
