version: 2
jobs:
  flake8:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: flake8
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox

  build:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: build
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox
      - store_artifacts:
          path: dist
          destination: packages
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: deploy
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: pip install --user tox
      - run: |
          export GITHUB_RELEASE_CICD_REPO="$(python setup.py --name)"
          export GITHUB_RELEASE_CICD_CREATE_NAME="$(python setup.py --version)"
          export GITHUB_RELEASE_CICD_CREATE_TAG="v${GITHUB_RELEASE_CICD_CREATE_NAME}"
          export GITHUB_RELEASE_CICD_CREATE_MESSAGE="$([ -z "${CIRCLE_TAG}" ] && git show --no-patch --pretty=format:%s%n%n%b ${CIRCLE_SHA1} || git tag --list --format="%(contents)" ${CIRCLE_TAG})"
          export GITHUB_RELEASE_CICD_CREATE_PRERELEASE="$([ -z "${CIRCLE_TAG}" ] && echo true || echo false)"
          export GITHUB_RELEASE_CICD_CREATE_TARGET="${CIRCLE_SHA1}"
          /home/circleci/.local/bin/tox -- '/tmp/workspace/dist/*'

workflows:
  version: 2
  test-and-build:
    jobs:
      - flake8:
          filters:
            tags:
              only: /^v[0-9.]*/
      - build:
          requires:
            - flake8
          filters:
            tags:
              only: /^v[0-9.]*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9.]*/
