# Autogenerated by Astropy-affiliated package ccdproc's setup.py on 2019-09-06 02:06:15 UTC
from __future__ import unicode_literals
import datetime

version = "2.0.1"
githash = "b7e0916a8772dae9523c5f07aebc5fd9eadfa3c2"


major = 2
minor = 0
bugfix = 1

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 9, 6, 2, 6, 15)
debug = False

astropy_helpers_version = "2.0.6"
