matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell  # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows  # Windows 10.0.17134 N/A Build 17134
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy3.5"
    - "pypy3.6"
    - "pypy3.7"
before_install:
    - python --version
    - uname -a
    - lsb_release -a
install:
    - make requirements
script:
    - make tests
notifications:
    email:
        on_success: never
        on_failure: always
