image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip install -U --force-reinstall twine
          - python setup.py sdist
          - python -m twine check dist/*

  tags:
    'v*':
      - step:
          script:
            - python setup.py sdist
            - pip install twine
            - twine upload dist/*
