# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      CONDA_CHANNELS: "glueviz"
      CONDA_DEPENDENCIES: "astropy scipy cython pyqt matplotlib h5py pygments pyzmq scikit-image pandas xlrd pillow pytest mock coverage ipython ipykernel qtconsole traitlets qtpy bottleneck"
      PIP_DEPENDENCIES: "mpl-scatter-density plotly<3.8 objgraph pytest-qt pytest-cov codecov"
      PIP_FALLBACK: "False"
      NUMPY_VERSION: "1.13"

  matrix:
      - PYTHON_VERSION: "2.7"
      - PYTHON_VERSION: "3.5"
      - PYTHON_VERSION: "3.6"

matrix:
    fast_finish: true

platform:
    -x64

install:

    # Install Miniconda
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Install to make sure entry points work
    - "python setup.py install"

    # List installed packages
    - "conda list"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% pytest --durations=20 --cov glue glue"
  - "%CMD_IN_ENV% codecov"
