#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['clima']

package_data = \
{'': ['*']}

install_requires = \
['fire==0.1.3']

setup(name='clima',
      version='0.1.0',
      description='Simple boilerplate for cli scripts',
      author='Joni Turunen',
      author_email='rojun.itu@gmail.com',
      url='https://github.com/d3rp/clima.git',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
