################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.org.matsim.api.core.v01
import javawrappers.org.matsim.withinday.replanning.identifiers.interfaces

from jpype.types import *
from typing import Union

from typing import overload

class ActivityEndIdentifierFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.tools.ActivityReplanningMap, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringActivityAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class ActivityPerformingIdentifier:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


class ActivityEndIdentifier:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


class ActivityPerformingIdentifierFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.tools.ActivityReplanningMap, arg1: javawrappers.org.matsim.withinday.mobsim.MobsimDataProvider, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringActivityAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class LeaveLinkIdentifier:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


class LeaveLinkIdentifierFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.tools.LinkReplanningMap, arg1: javawrappers.org.matsim.withinday.mobsim.MobsimDataProvider, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringLegAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class LegStartedIdentifier:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


class InitialIdentifierImpl:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


class LegStartedIdentifierFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.tools.LinkReplanningMap, arg1: javawrappers.org.matsim.withinday.mobsim.MobsimDataProvider, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringLegAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class LegPerformingIdentifierFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.tools.LinkReplanningMap, arg1: javawrappers.org.matsim.withinday.mobsim.MobsimDataProvider, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringLegAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class InitialIdentifierImplFactory:
	def __init__(self, arg0: javawrappers.org.matsim.withinday.mobsim.MobsimDataProvider, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.InitialIdentifier: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class LegPerformingIdentifier:
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...


