
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-01T18:30:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddd8bed519f22cc2f49e1fb432707378fc509c31",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
