[tool.poetry]
name = "tyme"
version = "0.1.0"
description = "track your moments everywhere"
authors = ["Enrico Borba <enricozb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
