[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "toml-sort"
version = "0.16.0"
description = "Toml sorting library"
authors = ["Sam Roeca <samuel.roeca@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/pappasam/toml-sort"
repository = "https://github.com/pappasam/toml-sort"
keywords = ["toml", "sort", "cli", "unix", "utility"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Utilities",
  "Typing :: Typed",
]
include = ["README.md"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
tomlkit = ">=0.5.5"
click = "^7.0"

[tool.poetry.scripts]
toml-sort = 'toml_sort.cli:cli'

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37
isolated_build = true
skipsdist = true
[testenv]
platform = linux
whitelist_externals = poetry
skip_install = true
commands =
  poetry install
  poetry run black --check --diff toml_sort tests
  poetry run mypy toml_sort
  poetry run pylint toml_sort tests
  poetry run pytest -vv
"""

[tool.black]
line-length = 79

[tool.poetry.dev-dependencies]
pylint = "^2.3"
black = {version = "^19.3b0", allows-prereleases = true}
mypy = "^0.720.0"
pre-commit = "^1.18"
tox = "^3.13"
pytest = "^5.0"
