# Config file for automatic testing at travis-ci.org

language: python
sudo: false
python:
  - "3.5"
  - "3.6"
    #  - "3.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install flake8 coveralls coverage

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=onebot setup.py test
  - make lint

after_success: coveralls

#  vim: set ts=4 sw=2 tw=80 et :
