dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: Gpnqa28rhJGWKcugzjlfShbBs+8rL5i85Fd6XVT9blwfkmmnBZ5Tiv8vEi4aWZ4MFfOn3odi0Kp3f4U1fzXV2OUtYbc2vdlsIY9Ltc2P9XINpoUG6HvO1edkS9ISnWgcR8dTAcI3eJZcPGEPCO3Vnjs7coMrElbS/2DinEycVwObNbesV1s/tV+uB0sXBRX5vQue4bgrbiPt/r+dr2sLO7cpZzyXoHNFhsj3wMNJV9+l5jHgmRfoc4rdky43FmKJGwCRVut9o/yQ9torBHOcTCW24lNFxN0IkdRLb24LPL/iKGeiI3wvfGlGxOXZ8PTeEO1qxvERy1jsI92ZKk1ME2G/Ple0OMppKM+B27bbdQ1nvBelINWWujhZdECznTaTe/4HXZzCb4vira5P461F81o6STHa6RCe5YukQKADcgU9A/JGdI5efbDRnmMB/2j2iVwRjlYRFwVmkEtjo9+djNWgD8Qpqn1e/7feK2NmSexVwVlpjPwtG2wd9fAVmGbRfN9/RZ3kC+NpXfHVv2EsNS25XxqePwFBbA3RgBjL3jmPlzEj5moJQa3qXW3Q/colCFzbDh9xG6K2kR5kGaQJ8u4ia95IubJUeOKTGiaqWWUBrK2KOPlc/4JU8gLbdN6sx/TdgzDj+7V+gqKyd/E4bR2ZjF+w4ITmsqfyxjrqa5E=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_cap1188/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-cap1188 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
