[tool.poetry]
name = "ip-geolocation-api"
version = "1.0.9"
description = "Free IP Geolocation API and IP Location Lookup Database by https://ipwhois.io"
authors = ["ipwhois.io"]

packages = [
    { include="pack" },
]

homepage = "https://ipwhois.io/"
documentation = "https://ipwhois.io/documentation"
readme = "README.md"

[tool.poetry.dependencies]
python = "2.7.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
pyipwhois = 'entry:main'
