# Workaround to bootstrap maturin on non-manylinux platforms
[build-system]
requires = ["setuptools~=41.2.0", "wheel~=0.33.6"]
build-backend = "setuptools.build_meta"

[tool.maturin]
bindings = "bin"
