################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.java.net
import javawrappers.org.jdom2.util
import javawrappers.org.jdom2
import javawrappers.org.jdom2.filter

from jpype.types import *
from typing import Union

from typing import overload

class LocatedDocType:
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def setElementName(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getElementName(self, ) -> javawrappers.java.lang.String: ...
	def getPublicID(self, ) -> javawrappers.java.lang.String: ...
	def getInternalSubset(self, ) -> javawrappers.java.lang.String: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def setSystemID(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	def setInternalSubset(self, arg0: javawrappers.java.lang.String, ) -> None: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Document: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getSystemID(self, ) -> javawrappers.java.lang.String: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def setPublicID(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...


class LocatedProcessingInstruction:
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.util.Map, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	def getPseudoAttributeValue(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def removePseudoAttribute(self, arg0: javawrappers.java.lang.String, ) -> Union[int, JBoolean]: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getTarget(self, ) -> javawrappers.java.lang.String: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	def setTarget(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	def getData(self, ) -> javawrappers.java.lang.String: ...
	def setPseudoAttribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def setData(self, arg0: javawrappers.java.util.Map, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def setData(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	def getPseudoAttributeNames(self, ) -> javawrappers.java.util.List: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...


class Located:
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...


class LocatedText:
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getText(self, ) -> javawrappers.java.lang.String: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def getTextTrim(self, ) -> javawrappers.java.lang.String: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def getTextNormalize(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Text: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	@staticmethod
	def normalizeString(arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def append(self, arg0: javawrappers.org.jdom2.Text, ) -> None: ...
	@overload
	def append(self, arg0: javawrappers.java.lang.String, ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...
	def setText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Text: ...


class LocatedJDOMFactory:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	@overload
	def docType(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def docType(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def docType(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def docType(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def docType(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, arg4: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	@overload
	def docType(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.DocType: ...
	def notifyAll(self, ) -> None: ...
	@overload
	def document(self, arg0: javawrappers.org.jdom2.Element, ) -> javawrappers.org.jdom2.Document: ...
	@overload
	def document(self, arg0: javawrappers.org.jdom2.Element, arg1: javawrappers.org.jdom2.DocType, ) -> javawrappers.org.jdom2.Document: ...
	@overload
	def document(self, arg0: javawrappers.org.jdom2.Element, arg1: javawrappers.org.jdom2.DocType, arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Document: ...
	def setRoot(self, arg0: javawrappers.org.jdom2.Document, arg1: javawrappers.org.jdom2.Element, ) -> None: ...
	@overload
	def entityRef(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, arg4: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def entityRef(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def entityRef(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def entityRef(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def entityRef(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def entityRef(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	def addContent(self, arg0: javawrappers.org.jdom2.Parent, arg1: javawrappers.org.jdom2.Content, ) -> None: ...
	def notify(self, ) -> None: ...
	@overload
	def cdata(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.CDATA: ...
	@overload
	def cdata(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.CDATA: ...
	def setAttribute(self, arg0: javawrappers.org.jdom2.Element, arg1: javawrappers.org.jdom2.Attribute, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def addNamespaceDeclaration(self, arg0: javawrappers.org.jdom2.Element, arg1: javawrappers.org.jdom2.Namespace, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def comment(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Comment: ...
	@overload
	def comment(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Comment: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: Union[int, JInt], arg3: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.org.jdom2.AttributeType, arg3: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: Union[int, JInt], ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def attribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.org.jdom2.AttributeType, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def text(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def text(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def element(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def element(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, arg4: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def processingInstruction(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def processingInstruction(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.util.Map, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def processingInstruction(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def processingInstruction(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def processingInstruction(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, arg3: javawrappers.java.util.Map, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...
	@overload
	def processingInstruction(self, arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.ProcessingInstruction: ...


class LocatedCDATA:
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getText(self, ) -> javawrappers.java.lang.String: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def getTextTrim(self, ) -> javawrappers.java.lang.String: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def getTextNormalize(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CDATA: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.CDATA: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	@staticmethod
	def normalizeString(arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def append(self, arg0: javawrappers.org.jdom2.Text, ) -> None: ...
	@overload
	def append(self, arg0: javawrappers.java.lang.String, ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...
	@overload
	def setText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Text: ...
	@overload
	def setText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.CDATA: ...


class LocatedComment:
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getText(self, ) -> javawrappers.java.lang.String: ...
	def notifyAll(self, ) -> None: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def notify(self, ) -> None: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Comment: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Comment: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...
	def setText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Comment: ...


class LocatedElement:
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	def getName(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def getAttributeValue(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def getAttributeValue(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def getAttributeValue(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.java.lang.String: ...
	@overload
	def getAttributeValue(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, arg2: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def removeChild(self, arg0: javawrappers.java.lang.String, ) -> Union[int, JBoolean]: ...
	@overload
	def removeChild(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> Union[int, JBoolean]: ...
	def removeNamespaceDeclaration(self, arg0: javawrappers.org.jdom2.Namespace, ) -> None: ...
	def coalesceText(self, arg0: Union[int, JBoolean], ) -> Union[int, JBoolean]: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	def indexOf(self, arg0: javawrappers.org.jdom2.Content, ) -> Union[int, JInt]: ...
	def getAttributes(self, ) -> javawrappers.java.util.List: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getText(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def getChild(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def getChild(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Element: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	@overload
	def removeContent(self, arg0: javawrappers.org.jdom2.filter.Filter, ) -> javawrappers.java.util.List: ...
	@overload
	def removeContent(self, arg0: javawrappers.org.jdom2.Content, ) -> Union[int, JBoolean]: ...
	@overload
	def removeContent(self, arg0: Union[int, JInt], ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def removeContent(self, ) -> javawrappers.java.util.List: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def isAncestor(self, arg0: javawrappers.org.jdom2.Element, ) -> Union[int, JBoolean]: ...
	@overload
	def getChildren(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.util.List: ...
	@overload
	def getChildren(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.java.util.List: ...
	@overload
	def getChildren(self, ) -> javawrappers.java.util.List: ...
	def getAdditionalNamespaces(self, ) -> javawrappers.java.util.List: ...
	@overload
	def getNamespace(self, ) -> javawrappers.org.jdom2.Namespace: ...
	@overload
	def getNamespace(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Namespace: ...
	@overload
	def getChildTextTrim(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.java.lang.String: ...
	@overload
	def getChildTextTrim(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	def sortAttributes(self, arg0: javawrappers.java.util.Comparator, ) -> None: ...
	def getNamespaceURI(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	def getXMLBaseURI(self, ) -> javawrappers.java.net.URI: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...
	def setName(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	@overload
	def setContent(self, arg0: Union[int, JInt], arg1: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Parent: ...
	@overload
	def setContent(self, arg0: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def setContent(self, arg0: Union[int, JInt], arg1: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def setContent(self, arg0: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def removeChildren(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> Union[int, JBoolean]: ...
	@overload
	def removeChildren(self, arg0: javawrappers.java.lang.String, ) -> Union[int, JBoolean]: ...
	def isRootElement(self, ) -> Union[int, JBoolean]: ...
	def notifyAll(self, ) -> None: ...
	@overload
	def getContent(self, arg0: Union[int, JInt], ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def getContent(self, arg0: javawrappers.org.jdom2.filter.Filter, ) -> javawrappers.java.util.List: ...
	@overload
	def getContent(self, ) -> javawrappers.java.util.List: ...
	def getContentSize(self, ) -> Union[int, JInt]: ...
	def setAttributes(self, arg0: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Element: ...
	def notify(self, ) -> None: ...
	def sortChildren(self, arg0: javawrappers.java.util.Comparator, ) -> None: ...
	def canContainContent(self, arg0: javawrappers.org.jdom2.Content, arg1: Union[int, JInt], arg2: Union[int, JBoolean], ) -> None: ...
	def getQualifiedName(self, ) -> javawrappers.java.lang.String: ...
	@overload
	def getDescendants(self, ) -> javawrappers.org.jdom2.util.IteratorIterable: ...
	@overload
	def getDescendants(self, arg0: javawrappers.org.jdom2.filter.Filter, ) -> javawrappers.org.jdom2.util.IteratorIterable: ...
	@overload
	def setAttribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def setAttribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def setAttribute(self, arg0: javawrappers.org.jdom2.Attribute, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def getAttribute(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Attribute: ...
	@overload
	def getAttribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Attribute: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def getNamespacePrefix(self, ) -> javawrappers.java.lang.String: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def hasAttributes(self, ) -> Union[int, JBoolean]: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	@overload
	def removeAttribute(self, arg0: javawrappers.java.lang.String, ) -> Union[int, JBoolean]: ...
	@overload
	def removeAttribute(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> Union[int, JBoolean]: ...
	@overload
	def removeAttribute(self, arg0: javawrappers.org.jdom2.Attribute, ) -> Union[int, JBoolean]: ...
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def cloneContent(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	@overload
	def addContent(self, arg0: Union[int, JInt], arg1: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def addContent(self, arg0: Union[int, JInt], arg1: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Parent: ...
	@overload
	def addContent(self, arg0: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def addContent(self, arg0: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Parent: ...
	@overload
	def addContent(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def addContent(self, arg0: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def addContent(self, arg0: javawrappers.java.util.Collection, ) -> javawrappers.org.jdom2.Parent: ...
	@overload
	def addContent(self, arg0: Union[int, JInt], arg1: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def addContent(self, arg0: Union[int, JInt], arg1: javawrappers.org.jdom2.Content, ) -> javawrappers.org.jdom2.Parent: ...
	def getTextTrim(self, ) -> javawrappers.java.lang.String: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def hasAdditionalNamespaces(self, ) -> Union[int, JBoolean]: ...
	@overload
	def getChildText(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.java.lang.String: ...
	@overload
	def getChildText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@overload
	def getChildTextNormalize(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.org.jdom2.Namespace, ) -> javawrappers.java.lang.String: ...
	@overload
	def getChildTextNormalize(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	def getTextNormalize(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Element: ...
	def addNamespaceDeclaration(self, arg0: javawrappers.org.jdom2.Namespace, ) -> Union[int, JBoolean]: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setNamespace(self, arg0: javawrappers.org.jdom2.Namespace, ) -> javawrappers.org.jdom2.Element: ...
	@overload
	def sortContent(self, arg0: javawrappers.java.util.Comparator, ) -> None: ...
	@overload
	def sortContent(self, arg0: javawrappers.org.jdom2.filter.Filter, arg1: javawrappers.java.util.Comparator, ) -> None: ...
	def setText(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.Element: ...


class LocatedEntityRef:
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, arg2: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ): ...
	@overload
	def __init__(self, arg0: javawrappers.java.lang.String, ): ...
	def setName(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getName(self, ) -> javawrappers.java.lang.String: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getPublicID(self, ) -> javawrappers.java.lang.String: ...
	def setColumn(self, arg0: Union[int, JInt], ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def setSystemID(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	def getNamespacesInherited(self, ) -> javawrappers.java.util.List: ...
	def getColumn(self, ) -> Union[int, JInt]: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Parent: ...
	@overload
	def getParent(self, ) -> javawrappers.org.jdom2.Element: ...
	def getSystemID(self, ) -> javawrappers.java.lang.String: ...
	def getParentElement(self, ) -> javawrappers.org.jdom2.Element: ...
	def getDocument(self, ) -> javawrappers.org.jdom2.Document: ...
	def getNamespacesInScope(self, ) -> javawrappers.java.util.List: ...
	def getLine(self, ) -> Union[int, JInt]: ...
	def setPublicID(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.jdom2.EntityRef: ...
	def getNamespacesIntroduced(self, ) -> javawrappers.java.util.List: ...
	def getValue(self, ) -> javawrappers.java.lang.String: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.CloneBase: ...
	@overload
	def clone(self, ) -> javawrappers.java.lang.Object: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def clone(self, ) -> javawrappers.org.jdom2.Content: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.EntityRef: ...
	@overload
	def detach(self, ) -> javawrappers.org.jdom2.Content: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def setLine(self, arg0: Union[int, JInt], ) -> None: ...
	def getCType(self, ) -> javawrappers.org.jdom2.Content.CType: ...


