
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-29T17:21:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "091596af5f6bc4916c218fcfd79dff74d9a70ba9",
 "version": "1.0.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
