[tool.poetry]
name = "django-imperavi-redactor"
version = "0.0.1"
description = "Django wrapper for use imperavi redactor."
authors = ["Dmitry Bastrikin <dima.bastrikin@bro.agency>"]
license = "MIT"

readme = 'README.rst'

keywords = ['django', 'imperavi', 'wysiwyg', 'redactor', 'editor',]

repository = "https://github.com/brogency/django-imperavi-redactor"
homepage = "https://github.com/brogency/django-imperavi-redactor"

[tool.poetry.dependencies]
python = "^3.5"
django = "^1.11 || ^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
