################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.org.ejml.data

from jpype.types import *
from typing import Union

from typing import overload

class GenericMatrixOps_F64:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	@staticmethod
	def isEquivalentTriangle(arg0: Union[int, JBoolean], arg1: javawrappers.org.ejml.data.DMatrix, arg2: javawrappers.org.ejml.data.DMatrix, arg3: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	@staticmethod
	def isEquivalent(arg0: javawrappers.org.ejml.data.DMatrix, arg1: javawrappers.org.ejml.data.DMatrix, arg2: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def isIdentity(arg0: javawrappers.org.ejml.data.DMatrix, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def setRandom(arg0: javawrappers.org.ejml.data.DMatrix, arg1: Union[float, JDouble], arg2: Union[float, JDouble], arg3: javawrappers.java.util.Random, ) -> None: ...
	@staticmethod
	def copy(arg0: javawrappers.org.ejml.data.DMatrix, arg1: javawrappers.org.ejml.data.DMatrix, ) -> None: ...
	def notify(self, ) -> None: ...


