[tool.poetry]
name = "gtk-file-chooser"
version = "0.2.0"
description = "A Simple Gtk File Chooser Dialog"
authors = ["BeatLink <beatlink@protonmail.com>"]
license = "GPL-3.0+"

packages = [{include = "file_chooser"}]

[tool.poetry.dependencies]
python = "^3.6"
pygobject = "^3.32.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
