
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-26T10:16:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9296945bf99c68c95cd2dcfc2457d1869fc782d",
 "version": "v0.6.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
