[tool.poetry]
name = "find_the_site"
version = "0.1.0"
description = "Find the site in duckduckgo"
authors = ["serhii <aserhii@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
beautifulsoup4 = "^4.7.1"
user-agent = "^0.1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
