################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.org.matsim.api.core.v01
import javawrappers.org.matsim.withinday.replanning.identifiers.interfaces

from jpype.types import *
from typing import Union

from typing import overload

class AgentFilterFactory:
	def createAgentFilter(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter: ...


class DuringActivityIdentifierFactory:
	def __init__(self, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringActivityAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class InitialIdentifierFactory:
	def __init__(self, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.InitialIdentifier: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class DuringLegAgentSelector:
	def __init__(self, ): ...
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...


class AgentSelector:
	def __init__(self, ): ...
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...


class DuringLegIdentifierFactory:
	def __init__(self, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.DuringLegAgentSelector: ...
	@overload
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class DuringActivityAgentSelector:
	def __init__(self, ): ...
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...


class AgentSelectorFactory:
	def __init__(self, ): ...
	def addAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def removeAgentFilterFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilterFactory, ) -> Union[int, JBoolean]: ...
	def createIdentifier(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelector: ...
	def notify(self, ) -> None: ...
	def getAgentFilterFactories(self, ) -> javawrappers.java.util.Set: ...


class AgentFilter:
	@overload
	def applyAgentFilter(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyAgentFilter(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...


class InitialIdentifier:
	def __init__(self, ): ...
	def addAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> None: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getAgentSelectorFactory(self, ) -> javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	def getAgentFilters(self, ) -> javawrappers.java.util.Set: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	def applyFilters(self, arg0: javawrappers.java.util.Set, arg1: Union[float, JDouble], ) -> None: ...
	@overload
	def applyFilters(self, arg0: javawrappers.org.matsim.api.core.v01.Id, arg1: Union[float, JDouble], ) -> Union[int, JBoolean]: ...
	def setAgentSelectorFactory(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentSelectorFactory, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def getAgentsToReplan(self, arg0: Union[float, JDouble], ) -> javawrappers.java.util.Set: ...
	def removeAgentFilter(self, arg0: javawrappers.org.matsim.withinday.replanning.identifiers.interfaces.AgentFilter, ) -> Union[int, JBoolean]: ...


