---
- name: Ensure the Kolla configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0750
  become: True
  with_items:
    - "{{ kolla_build_config_path }}"
