#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fissle']

package_data = \
{'': ['*']}

install_requires = \
['fire']

setup(name='fissle',
      version='0.0.3',
      description='"Slim boilerplate for cli scripts',
      author='Joni Turunen',
      author_email='rojun.itu@gmail.com',
      url='https://github.com/d3rp/fissle.git',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
