# coding: utf-8

"""
    ACI Services API

    API for methods pertaining to all ACI services  # noqa: E501

    OpenAPI spec version: 3.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VehicleRiskRequestAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'effective_end_date': 'date',
        'reference_number': 'str',
        'vin': 'str'
    }

    attribute_map = {
        'effective_end_date': 'effectiveEndDate',
        'reference_number': 'referenceNumber',
        'vin': 'vin'
    }

    def __init__(self, effective_end_date=None, reference_number=None, vin=None):  # noqa: E501
        """VehicleRiskRequestAttribute - a model defined in Swagger"""  # noqa: E501

        self._effective_end_date = None
        self._reference_number = None
        self._vin = None
        self.discriminator = None

        if effective_end_date is not None:
            self.effective_end_date = effective_end_date
        if reference_number is not None:
            self.reference_number = reference_number
        self.vin = vin

    @property
    def effective_end_date(self):
        """Gets the effective_end_date of this VehicleRiskRequestAttribute.  # noqa: E501

        the effective end date  # noqa: E501

        :return: The effective_end_date of this VehicleRiskRequestAttribute.  # noqa: E501
        :rtype: date
        """
        return self._effective_end_date

    @effective_end_date.setter
    def effective_end_date(self, effective_end_date):
        """Sets the effective_end_date of this VehicleRiskRequestAttribute.

        the effective end date  # noqa: E501

        :param effective_end_date: The effective_end_date of this VehicleRiskRequestAttribute.  # noqa: E501
        :type: date
        """

        self._effective_end_date = effective_end_date

    @property
    def reference_number(self):
        """Gets the reference_number of this VehicleRiskRequestAttribute.  # noqa: E501

        the reference number for the caller's tracking purposes  # noqa: E501

        :return: The reference_number of this VehicleRiskRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """Sets the reference_number of this VehicleRiskRequestAttribute.

        the reference number for the caller's tracking purposes  # noqa: E501

        :param reference_number: The reference_number of this VehicleRiskRequestAttribute.  # noqa: E501
        :type: str
        """

        self._reference_number = reference_number

    @property
    def vin(self):
        """Gets the vin of this VehicleRiskRequestAttribute.  # noqa: E501

        the vehicle identification number  # noqa: E501

        :return: The vin of this VehicleRiskRequestAttribute.  # noqa: E501
        :rtype: str
        """
        return self._vin

    @vin.setter
    def vin(self, vin):
        """Sets the vin of this VehicleRiskRequestAttribute.

        the vehicle identification number  # noqa: E501

        :param vin: The vin of this VehicleRiskRequestAttribute.  # noqa: E501
        :type: str
        """
        if vin is None:
            raise ValueError("Invalid value for `vin`, must not be `None`")  # noqa: E501

        self._vin = vin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VehicleRiskRequestAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
