
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-25T18:57:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "72d73fc6a998b92e7a036ac934972e80bf74ee73",
 "version": "v0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
