---
# This file holds the config given to Tenks when running `tenks-deploy.sh`. It
# assumes the existence of the bridge `breth1`.

node_types:
  type0:
    memory_mb: 3072
    vcpus: 1
    volumes:
      # There is a minimum disk space capacity requirement of 4GiB when using Ironic Python Agent:
      # https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/utils.py#L290
      # The CentOS7 cloud image seems to fill a 4GiB disk, so allow 6.
      - capacity: 6GiB
    physical_networks:
      - physnet1
    console_log_enabled: true

specs:
  - type: type0
    count: 1
    ironic_config:
      resource_class: test-rc
      network_interface: noop

node_name_prefix: controller

nova_flavors: []

physnet_mappings:
  physnet1: breth1

# No placement service.
wait_for_placement: false

# Nested virtualisation is not working well in CI currently. Force the use of
# QEMU.
libvirt_vm_engine: "qemu"
