
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-29T01:47:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f716c8ab9b7074d3aad85fb75409d14a8411e0d9",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
