
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-05T12:47:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b5304ede8c25f17ce3875ebe4887ca8bac2cf49",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
