[tool.poetry]
name = "jrpyvisualisation"
version = "0.1.4"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
plotly = "^4.1"
pandas = "^0.25.0"
numpy = "^1.17"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
