
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-27T16:33:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e659b741a31f0ec2f1c5a5bf07f4697855dcff7",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
