
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-27T15:00:01+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "864bd2a79ac4b9d168cfe52a464803a2c7138e62",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
