# coding: utf-8

# flake8: noqa
"""
    EO Service

    The Enterprise Ontology (EO) aims at establishing a common conceptualization on the Entreprise domain, including organizations, organizational units, people, roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from eo_client.models.atomic_project_ import AtomicProject_
from eo_client.models.complex_project_ import ComplexProject_
from eo_client.models.organization_team_ import OrganizationTeam_
from eo_client.models.organization_ import Organization_
from eo_client.models.organizational_role_ import OrganizationalRole_
from eo_client.models.person_ import Person_
from eo_client.models.project_team_ import ProjectTeam_
from eo_client.models.project_ import Project_
from eo_client.models.team_member_ import TeamMember_
from eo_client.models.team_membership_ import TeamMembership_
from eo_client.models.team_purpose_ import TeamPurpose_
from eo_client.models.team_ import Team_
