
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-03T18:02:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "53ab7dee152e25ba225da6d31455a1749b5c9dce",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
