# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PipelineCreationInfo(Model):
    """PipelineCreationInfo.

    :param name:
    :type name: str
    :param description:
    :type description: str
    :param version:
    :type version: str
    :param graph:
    :type graph: ~swagger.models.GraphEntity
    :param graph_interface:
    :type graph_interface: ~swagger.models.EntityInterface
    :param parameter_assignments:
    :type parameter_assignments: dict[str, str]
    :param data_path_assignments:
    :type data_path_assignments: dict[str, ~swagger.models.LegacyDataPath]
    :param data_set_definition_value_assignments:
    :type data_set_definition_value_assignments: dict[str,
     ~swagger.models.DataSetDefinitionValue]
    :param continue_run_on_step_failure:
    :type continue_run_on_step_failure: bool
    :param properties:
    :type properties: dict
    """

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'description': {'key': 'Description', 'type': 'str'},
        'version': {'key': 'Version', 'type': 'str'},
        'graph': {'key': 'Graph', 'type': 'GraphEntity'},
        'graph_interface': {'key': 'GraphInterface', 'type': 'EntityInterface'},
        'parameter_assignments': {'key': 'ParameterAssignments', 'type': '{str}'},
        'data_path_assignments': {'key': 'DataPathAssignments', 'type': '{LegacyDataPath}'},
        'data_set_definition_value_assignments': {'key': 'DataSetDefinitionValueAssignments', 'type': '{DataSetDefinitionValue}'},
        'continue_run_on_step_failure': {'key': 'ContinueRunOnStepFailure', 'type': 'bool'},
        'properties': {'key': 'Properties', 'type': '{object}'},
    }

    def __init__(self, name=None, description=None, version=None, graph=None, graph_interface=None, parameter_assignments=None, data_path_assignments=None, continue_run_on_step_failure=None, data_set_definition_value_assignments=None, properties=None):
        super(PipelineCreationInfo, self).__init__()
        self.name = name
        self.description = description
        self.version = version
        self.graph = graph
        self.graph_interface = graph_interface
        self.parameter_assignments = parameter_assignments
        self.data_path_assignments = data_path_assignments
        self.data_set_definition_value_assignments = data_set_definition_value_assignments
        self.continue_run_on_step_failure = continue_run_on_step_failure
        self.properties = properties
