################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang.reflect
import javawrappers.java.lang
import javawrappers.org.aopalliance.intercept

from jpype.types import *
from typing import Union

from typing import overload

class Invocation:
	def getThis(self, ) -> javawrappers.java.lang.Object: ...
	def proceed(self, ) -> javawrappers.java.lang.Object: ...
	def getArguments(self, ) -> JArray(javawrappers.java.lang.Object, 1): ...
	def getStaticPart(self, ) -> javawrappers.java.lang.reflect.AccessibleObject: ...


class ConstructorInterceptor:
	def construct(self, arg0: javawrappers.org.aopalliance.intercept.ConstructorInvocation, ) -> javawrappers.java.lang.Object: ...


class MethodInvocation:
	def getThis(self, ) -> javawrappers.java.lang.Object: ...
	def proceed(self, ) -> javawrappers.java.lang.Object: ...
	def getArguments(self, ) -> JArray(javawrappers.java.lang.Object, 1): ...
	def getMethod(self, ) -> javawrappers.java.lang.reflect.Method: ...
	def getStaticPart(self, ) -> javawrappers.java.lang.reflect.AccessibleObject: ...


class Joinpoint:
	def getThis(self, ) -> javawrappers.java.lang.Object: ...
	def proceed(self, ) -> javawrappers.java.lang.Object: ...
	def getStaticPart(self, ) -> javawrappers.java.lang.reflect.AccessibleObject: ...


class ConstructorInvocation:
	def getThis(self, ) -> javawrappers.java.lang.Object: ...
	def proceed(self, ) -> javawrappers.java.lang.Object: ...
	def getArguments(self, ) -> JArray(javawrappers.java.lang.Object, 1): ...
	def getStaticPart(self, ) -> javawrappers.java.lang.reflect.AccessibleObject: ...
	def getConstructor(self, ) -> javawrappers.java.lang.reflect.Constructor: ...


class MethodInterceptor:
	def invoke(self, arg0: javawrappers.org.aopalliance.intercept.MethodInvocation, ) -> javawrappers.java.lang.Object: ...


class Interceptor:


