
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-26T13:53:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d43a3bc980f2c58b146400e01d6f5f46440fd83f",
 "version": "0.3.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
