
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T10:54:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4e84e5f6278e4508d94d2988ba12c419650b611",
 "version": "2019.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
