
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-27T12:58:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8c29f75b558fb885d262552d9b14a39ccde5b2d",
 "version": "0.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
