[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "cjdg_api"
author = "Rqk"
author-email = "renqiukai@qq.com"
home-page = "http://www.chaojidaogou.com"
classifiers = ["License :: OSI Approved :: MIT License"]

