
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "44a0447db211f55e3c697b3dcdd5937f04eb4dba",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
