# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ncbi.cloudblast.v1alpha import api_pb2 as ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2


class CloudBlastStub(object):
  """RPC methods for CloudBlast public API
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitSearch = channel.unary_unary(
        '/ncbi.cloudblast.v1alpha.CloudBlast/SubmitSearch',
        request_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.SubmitRequest.SerializeToString,
        response_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.SubmitReply.FromString,
        )
    self.GetStatus = channel.unary_unary(
        '/ncbi.cloudblast.v1alpha.CloudBlast/GetStatus',
        request_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.StatusRequest.SerializeToString,
        response_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.StatusReply.FromString,
        )
    self.Results = channel.unary_unary(
        '/ncbi.cloudblast.v1alpha.CloudBlast/Results',
        request_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.ResultRequest.SerializeToString,
        response_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.ResultReply.FromString,
        )
    self.GetDBCatalog = channel.unary_unary(
        '/ncbi.cloudblast.v1alpha.CloudBlast/GetDBCatalog',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.DBCatalog.FromString,
        )


class CloudBlastServicer(object):
  """RPC methods for CloudBlast public API
  """

  def SubmitSearch(self, request, context):
    """Submit a BLAST search request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatus(self, request, context):
    """Get BLAST search status
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Results(self, request, context):
    """Get BLAST search result
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDBCatalog(self, request, context):
    """Get the full list of available BLAST databases
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudBlastServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitSearch': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitSearch,
          request_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.SubmitRequest.FromString,
          response_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.SubmitReply.SerializeToString,
      ),
      'GetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatus,
          request_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.StatusRequest.FromString,
          response_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.StatusReply.SerializeToString,
      ),
      'Results': grpc.unary_unary_rpc_method_handler(
          servicer.Results,
          request_deserializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.ResultRequest.FromString,
          response_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.ResultReply.SerializeToString,
      ),
      'GetDBCatalog': grpc.unary_unary_rpc_method_handler(
          servicer.GetDBCatalog,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=ncbi_dot_cloudblast_dot_v1alpha_dot_api__pb2.DBCatalog.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ncbi.cloudblast.v1alpha.CloudBlast', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
