---
- project:
    templates:
      - build-openstack-sphinx-docs
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python-jobs
    check:
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos

    gate:
      queue: kayobe
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos
