
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-21T16:08:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2153163a5cdbc1841c54e255aa5699a5c8082acf",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
