[tool.poetry]
name = "jrpyintroduction"
version = "0.1.3"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
pandas = ">= 0.20.1, < 0.24"
numpy = "^1.14.4"
matplotlib = "^3.1"


[tool.poetry.dev-dependencies]
pytest = "^3.0"
