language: python

python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "nightly"
    - "pypy"
    - "pypy3"

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - python setup.py install

script: nosetests -s
