dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: m2YkBNLO2NFz4ZKpQNW/+m5Wc1/W2aP24BOu9TpoJlE0pUPtag0GUFzOb2roHDbUzLl7y0anHaVVcsVztZyS0b64KiNzZ2iWdN39S5X0nsq0aQAKcKI6TTNl//IPIn23LgrzjQF05k8YKKuY3QnSz9oo3inswVOEeQbZwkPtaVHiJgL9uCqdivy82xyjrnoxgfy1V587tvQwpiJ0Tc10seyyuBjzw33Zb5hgJGsWeS8fuqTl/8nnUGDXCnNPPyyHkxYLjDrbH9x87Hp+eR8URctwrjIn39o4uuF3pgmnmEA1u5fpKyCGuVAsLSlSvmYPzkf0fLD3YDpws4KEm2dr9bBX+x0SlZMpRKr+snW+nzMtK0ltZKOBBS9g1suohOo5qjexNl70ykLU7OchKWCmAWclRlP3GWnpX2gcKGk+fzvv5OqKFI8+6UMcOHLOLzsPkl/9hMisci+VijBIUs7rZckAy2terRayqqwOEq15j3YLCTzlLP1vIfPc8S6ukH1A6+rEoNvGMqmCIAQntbQSwzjgL+4xAlfc5SDBQG9+dKANHCH4zJlKnXfbLxn3SMchtPr8jz6JE/UtOTc7+/9as8bOxfre3ElCPzDZv6M3k5CQHr+hANAepQR8Om86aRry7a7vYym/ESoJdqBURpmq6/+/I2bxnj/1MqlGRahPx1U=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_mlx90393.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit_circuitpython_mlx90393 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
