################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.java.util
import javawrappers.org.opengis.util

from jpype.types import *
from typing import Union

from typing import overload

class Text:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def text(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.util.Map, ) -> javawrappers.org.opengis.util.InternationalString: ...
	@overload
	@staticmethod
	def text(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.util.Properties, ) -> javawrappers.org.opengis.util.InternationalString: ...
	@overload
	@staticmethod
	def text(arg0: javawrappers.java.lang.String, ) -> javawrappers.org.opengis.util.InternationalString: ...
	@overload
	@staticmethod
	def text(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.opengis.util.InternationalString: ...
	def notify(self, ) -> None: ...


