[tool.poetry]
name = "lethargy"
version = "0.1.0"
description = "A minimal library to make your option-parsing easier."
license = "MIT"
repository = "https://github.com/SeparateRecords/lethargy"
authors = ["SeparateRecords <separaterecords@users.noreply.github.com>"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
    
]
keywords = [
    "CLI",
    "options",
    "minimal",
]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
