[tool.poetry]
name = "cc-faice"
version = "8.0.0"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/cc-faice"
homepage = "https://www.curious-containers.cc/"
description = "FAICE (Fair Collaboration and Experiments) is part of the Curious Containers project and enables researchers to perform and distribute reproducible data-driven experiments defined in RED or CWL format."

[tool.poetry.dependencies]
python = "^3.5"
docker = "^4.0"
keyring = "^19.0"
jsonschema = "^3.0"
cc-core = "~8.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
faice = 'cc_faice.main:main'
