application: oggenc
version_arg: --version
inout_args: --quiet -o "{outfile}" "{infile}"

extension: ogg
default: mixed, complex, stereo

combinations:

  # Speech
  speech, simple, mono:      --advanced-encode-option lowpass_frequency=13000 --bitrate 44 --downmix
  speech, moderate, mono:    --advanced-encode-option lowpass_frequency=14000 --bitrate 50 --downmix
  speech, complex, mono:     --advanced-encode-option lowpass_frequency=16000 --bitrate 52 --downmix
  speech, simple, stereo:    --advanced-encode-option lowpass_frequency=13000 --bitrate 50
  speech, moderate, stereo:  --advanced-encode-option lowpass_frequency=14000 --bitrate 56
  speech, complex, stereo:   --advanced-encode-option lowpass_frequency=16000 --quality 1.4

  # Music
  music, simple, mono:       --quality 2.2 --downmix
  music, moderate, mono:     --quality 2.3 --downmix
  music, complex, mono:      --quality 2.5 --downmix
  music, simple, stereo:     --quality 3.5
  music, moderate, stereo:   --quality 4.3
  music, complex, stereo:    --quality 5.0

  # Mixed
  mixed, simple, mono:       --quality 2.1 --downmix
  mixed, moderate, mono:     --quality 2.2 --downmix
  mixed, complex, mono:      --quality 2.3 --downmix
  mixed, simple, stereo:     --quality 3.2
  mixed, moderate, stereo:   --quality 4.0
  mixed, complex, stereo:    --quality 4.5

  # Effects
  effects, simple, mono:     --quality 1.5 --downmix
  effects, moderate, mono:   --quality 1.7 --downmix
  effects, complex, mono:    --quality 2.0 --downmix
  effects, simple, stereo:   --quality 2.5
  effects, moderate, stereo: --quality 3.0
  effects, complex, stereo:  --quality 4.0

  # Filler
  filler, simple, mono:      --quality -1 --resample 512 --downmix
  filler, moderate, mono:    --quality -1 --resample 512 --downmix
  filler, complex, mono:     --quality -1 --resample 512 --downmix
  filler, simple, stereo:    --quality -1 --resample 512 --downmix
  filler, moderate, stereo:  --quality -1 --resample 512 --downmix
  filler, complex, stereo:   --quality -1 --resample 512 --downmix
