
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-31T17:43:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b0f424f02a3c4456cae3b6dfe77d5e52c18cc7a",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
