language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install qmpy_rester
script:
    python setup.py test
env:
    oqmd_url=http://amglab.ms.northwestern.edu:8000
