[tool.black]
line-length = 88
target-version = ['py36', 'py37']

[tool.poetry]
name = "roax-geo"
module = "roax.geo"
version = "1.0.1"
description = "Geographic extension for Roax."
readme = "README.md"
authors = ["Paul Bryan <pbryan@anode.ca>"]
homepage = "https://github.com/roax/roax-geo/"
documentation = "https://github.com/roax/roax-geo/wiki"
license = "MIT"
keywords = ["wsgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
packages = [
    { include = "roax" }
]

[tool.poetry.dependencies]
python = "^3.6 <3.8"
roax = "^1.3"
geomet = "^0.2"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
pre-commit = "^1.18"
pytest = "^5.1"
pytest-cov = "^2.7"
