
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-23T23:11:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6f8918bfee44500cd0a66fc8a5637d981c0ac86",
 "version": "2019.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
