
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-05T11:45:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e00d4cbfa0268458a7b05644b24d2d8360d58875",
 "version": "0.19.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
