# coding: utf-8

"""
    ACI Services API

    API for methods pertaining to all ACI services  # noqa: E501

    OpenAPI spec version: 3.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import autocheckinsurance
from autocheckinsurance.models.risk_calculation_plus_response import RiskCalculationPlusResponse  # noqa: E501
from autocheckinsurance.rest import ApiException


class TestRiskCalculationPlusResponse(unittest.TestCase):
    """RiskCalculationPlusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskCalculationPlusResponse(self):
        """Test RiskCalculationPlusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = autocheckinsurance.models.risk_calculation_plus_response.RiskCalculationPlusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
