
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-22T17:28:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7bed5aba7fdeb8e61a7409713142d0ed6d94b01",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
