[tool.poetry]
name = "blackini"
version = "0.1.4"
description = ""
authors = ["Pablo Woolvett <pablowoolvett@gmail.com>"]

[tool.poetry.scripts]
black = "blackini.__main__:main"

[tool.poetry.dependencies]
python = "^3.6"
black = { version = "^19.3b0"}

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
