
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-23T15:31:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "711f6fe04fb06280d452ee695226883e73eb2f01",
 "version": "v0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
