# coding: utf-8

"""
    EO Service

    The Enterprise Ontology (EO) aims at establishing a common conceptualization on the Entreprise domain, including organizations, organizational units, people, roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eo_client
from eo_client.api.team_members_api import TeamMembersApi  # noqa: E501
from eo_client.rest import ApiException


class TestTeamMembersApi(unittest.TestCase):
    """TeamMembersApi unit test stubs"""

    def setUp(self):
        self.api = eo_client.api.team_members_api.TeamMembersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_team_members_create(self):
        """Test case for team_members_create

        """
        pass

    def test_team_members_delete(self):
        """Test case for team_members_delete

        """
        pass

    def test_team_members_list(self):
        """Test case for team_members_list

        """
        pass

    def test_team_members_partial_update(self):
        """Test case for team_members_partial_update

        """
        pass

    def test_team_members_read(self):
        """Test case for team_members_read

        """
        pass

    def test_team_members_update(self):
        """Test case for team_members_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
