- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
