################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.org.w3c.dom
import javawrappers.com.sun.xml.bind.v2.runtime.unmarshaller
import javawrappers.org.xml.sax
import javawrappers.javax.xml.bind

from jpype.types import *
from typing import Union

from typing import overload

class Messages:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@overload
	@staticmethod
	def format(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.Object, arg2: javawrappers.java.lang.Object, ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def format(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.Object, arg2: javawrappers.java.lang.Object, arg3: javawrappers.java.lang.Object, ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def format(arg0: javawrappers.java.lang.String, arg1: JArray(javawrappers.java.lang.Object, 1), ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def format(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.Object, ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def format(arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def notify(self, ) -> None: ...


class InfosetScanner:
	def setContentHandler(self, arg0: javawrappers.org.xml.sax.ContentHandler, ) -> None: ...
	def getContentHandler(self, ) -> javawrappers.org.xml.sax.ContentHandler: ...
	def scan(self, arg0: javawrappers.java.lang.Object, ) -> None: ...
	def getLocator(self, ) -> javawrappers.com.sun.xml.bind.v2.runtime.unmarshaller.LocatorEx: ...
	def getCurrentElement(self, ) -> javawrappers.java.lang.Object: ...


class Patcher:
	def run(self, ) -> None: ...


class DOMScanner:
	def __init__(self, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def getLocation(self, ) -> javawrappers.javax.xml.bind.ValidationEventLocator: ...
	def getSystemId(self, ) -> javawrappers.java.lang.String: ...
	def notifyAll(self, ) -> None: ...
	@overload
	def scan(self, arg0: javawrappers.java.lang.Object, ) -> None: ...
	@overload
	def scan(self, arg0: javawrappers.org.w3c.dom.Element, ) -> None: ...
	@overload
	def scan(self, arg0: javawrappers.org.w3c.dom.Document, ) -> None: ...
	def getColumnNumber(self, ) -> Union[int, JInt]: ...
	def parse(self, arg0: javawrappers.org.w3c.dom.Element, arg1: javawrappers.org.xml.sax.ContentHandler, ) -> None: ...
	def notify(self, ) -> None: ...
	def getCurrentElement(self, ) -> javawrappers.java.lang.Object: ...
	def getPublicId(self, ) -> javawrappers.java.lang.String: ...
	def getLineNumber(self, ) -> Union[int, JInt]: ...
	def setContentHandler(self, arg0: javawrappers.org.xml.sax.ContentHandler, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def getContentHandler(self, ) -> javawrappers.org.xml.sax.ContentHandler: ...
	def parseWithContext(self, arg0: javawrappers.org.w3c.dom.Element, arg1: javawrappers.org.xml.sax.ContentHandler, ) -> None: ...
	def getLocator(self, ) -> javawrappers.com.sun.xml.bind.v2.runtime.unmarshaller.LocatorEx: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def visit(self, arg0: javawrappers.org.w3c.dom.Element, ) -> None: ...
	def getCurrentLocation(self, ) -> javawrappers.org.w3c.dom.Node: ...
	def setLocator(self, arg0: javawrappers.org.xml.sax.Locator, ) -> None: ...


