
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-20T12:48:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dedf3b8d11d3698f2e23b3c806ee127919a4ce3",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
