################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.awt
import javawrappers.java.lang
import javawrappers.java.text
import javawrappers.java.net
import javawrappers.java.io
import javawrappers.java.awt.geom
import javawrappers.org.jfree.io

from jpype.types import *
from typing import Union

from typing import overload

class IOUtils:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def notifyAll(self, ) -> None: ...
	def createRelativeURL(self, arg0: javawrappers.java.net.URL, arg1: javawrappers.java.net.URL, ) -> javawrappers.java.lang.String: ...
	@overload
	def copyStreams(self, arg0: javawrappers.java.io.InputStream, arg1: javawrappers.java.io.OutputStream, ) -> None: ...
	@overload
	def copyStreams(self, arg0: javawrappers.java.io.InputStream, arg1: javawrappers.java.io.OutputStream, arg2: Union[int, JInt], ) -> None: ...
	def notify(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def isSubDirectory(self, arg0: javawrappers.java.io.File, arg1: javawrappers.java.io.File, ) -> Union[int, JBoolean]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def getFileExtension(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def stripFileExtension(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def getInstance() -> javawrappers.org.jfree.io.IOUtils: ...
	def getFileName(self, arg0: javawrappers.java.net.URL, ) -> javawrappers.java.lang.String: ...
	@overload
	def copyWriter(self, arg0: javawrappers.java.io.Reader, arg1: javawrappers.java.io.Writer, ) -> None: ...
	@overload
	def copyWriter(self, arg0: javawrappers.java.io.Reader, arg1: javawrappers.java.io.Writer, arg2: Union[int, JInt], ) -> None: ...


class FileUtilities:
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def findFileOnClassPath(arg0: javawrappers.java.lang.String, ) -> javawrappers.java.io.File: ...
	def notify(self, ) -> None: ...


class SerialUtilities:
	@staticmethod
	def readPoint2D(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.awt.geom.Point2D: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@staticmethod
	def readStroke(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.awt.Stroke: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	@staticmethod
	def writeComposite(arg0: javawrappers.java.awt.Composite, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	@staticmethod
	def writeShape(arg0: javawrappers.java.awt.Shape, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	@staticmethod
	def writePaint(arg0: javawrappers.java.awt.Paint, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	def notifyAll(self, ) -> None: ...
	def notify(self, ) -> None: ...
	@staticmethod
	def writeAttributedString(arg0: javawrappers.java.text.AttributedString, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	@staticmethod
	def readPaint(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.awt.Paint: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def isSerializable(arg0: javawrappers.java.lang.Class, ) -> Union[int, JBoolean]: ...
	@staticmethod
	def writePoint2D(arg0: javawrappers.java.awt.geom.Point2D, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	@staticmethod
	def readShape(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.awt.Shape: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def readAttributedString(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.text.AttributedString: ...
	@staticmethod
	def writeStroke(arg0: javawrappers.java.awt.Stroke, arg1: javawrappers.java.io.ObjectOutputStream, ) -> None: ...
	@staticmethod
	def readComposite(arg0: javawrappers.java.io.ObjectInputStream, ) -> javawrappers.java.awt.Composite: ...


