---
# Roughly follows kolla-ansible's service deployment patterns.

# Action to perform. One of 'deploy', 'destroy', 'pull', 'reconfigure',
# 'upgrade'.
nodeexporter_action: deploy

# Whether Node Exporter is enabled.
nodeexporter_enabled: false

# Service deployment definition.
nodeexporter_services:
  nodeexporter:
    container_name: nodeexporter
    enabled: "{{ nodeexporter_enabled }}"
    image: "{{ nodeexporter_image_full }}"
    command: --path.procfs=/host/proc --path.sysfs=/host/sys --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)" --collector.ntp
    privileged: True
    read_only: True
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
      - "/etc/hostname:/etc/host_hostname"

####################
# Docker
####################
nodeexporter_namespace: "prom"
nodeexporter_image: "{{ docker_registry ~ '/' if docker_registry | default else '' }}{{ nodeexporter_namespace }}/node-exporter"
nodeexporter_tag: "v0.15.0"
nodeexporter_image_full: "{{ nodeexporter_image }}:{{ nodeexporter_tag }}"

nodeexporter_restart_policy: "unless-stopped"
#nodeexporter_restart_retries: 10
