
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-30T17:22:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "52b9c2051e9e9cbdca7a98f45b48c4dad4a79d2e",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
