[tool.poetry]
name = "zabbix_controller"
version = "0.1.19"
description = ""
authors = ["hamadakafu <kafu.h1998@gmail.com>"]
readme = "README.md"
repository = "https://github.com/hamadakafu/zabbix-controller"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
pyzabbix = "^0.7.5"
bullet = "^2.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.3"
autopep8 = "^1.4"
pyinstaller = "^3.5"
macholib = "^1.11"

[tool.poetry.scripts]
# zabbix_controllerディレクトリのzabbix_controllerファイルのcall_command関数を実行
zabbixctl = "zabbix_controller.call_command:call_command"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
