################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.org.hsqldb.result
import javawrappers.org.hsqldb

from jpype.types import *
from typing import Union

from typing import overload

class ErrorCode:


class Error:
	def __init__(self, ): ...
	@staticmethod
	def runtimeError(arg0: Union[int, JInt], arg1: javawrappers.java.lang.String, ) -> javawrappers.java.lang.RuntimeException: ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def notifyAll(self, ) -> None: ...
	@overload
	@staticmethod
	def parseError(arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: Union[int, JInt], arg3: JArray(javawrappers.java.lang.Object, 1), ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def parseError(arg0: Union[int, JInt], arg1: javawrappers.java.lang.String, arg2: Union[int, JInt], ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def getMessage(arg0: Union[int, JInt], ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def getMessage(arg0: Union[int, JInt], arg1: Union[int, JInt], arg2: JArray(javawrappers.java.lang.Object, 1), ) -> javawrappers.java.lang.String: ...
	@overload
	@staticmethod
	def error(arg0: javawrappers.java.lang.Throwable, arg1: Union[int, JInt], arg2: javawrappers.java.lang.String, ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: javawrappers.org.hsqldb.result.Result, ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: Union[int, JInt], arg1: javawrappers.java.lang.String, ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: javawrappers.java.lang.String, arg1: javawrappers.java.lang.String, ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: Union[int, JInt], arg1: Union[int, JInt], ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: javawrappers.java.lang.Throwable, arg1: Union[int, JInt], arg2: Union[int, JInt], arg3: JArray(javawrappers.java.lang.Object, 1), ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: Union[int, JInt], arg1: javawrappers.java.lang.Throwable, ) -> javawrappers.org.hsqldb.HsqlException: ...
	@overload
	@staticmethod
	def error(arg0: Union[int, JInt], ) -> javawrappers.org.hsqldb.HsqlException: ...
	def notify(self, ) -> None: ...
	@staticmethod
	def getStateString(arg0: Union[int, JInt], ) -> javawrappers.java.lang.String: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	@staticmethod
	def printSystemOut(arg0: javawrappers.java.lang.String, ) -> None: ...
	@staticmethod
	def getCode(arg0: javawrappers.java.lang.String, ) -> Union[int, JInt]: ...


