
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-21T18:04:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca41e6df8ecda4c4fa6599d2d5fc4c99a58b8262",
 "version": "2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
