# -*- coding: utf-8 -*-

"""
    api_tester_upload_test

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from api_tester_upload_test.api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # True if the client should skip verification of SSL certificates
    skip_ssl_verification = False

    # An enum for SDK environments
    class Environment(object):
        PRODUCTION = 0

    # An enum for API servers
    class Server(object):
        EXPIRED = 0
        WRONG_HOST = 1
        SELF_SIGNED = 2
        UNTRUSTED_ROOT = 3
        REVOKED = 4
        PINNING_TEST = 5

    # The environment in which the SDK is running
    environment = Environment.PRODUCTION


    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.EXPIRED: 'https://expired.badssl.com',
            Server.WRONG_HOST: 'https://wrong.host.badssl.com',
            Server.SELF_SIGNED: 'https://self-signed.badssl.com',
            Server.UNTRUSTED_ROOT: 'https://untrusted-root.badssl.com',
            Server.REVOKED: 'https://revoked.badssl.com',
            Server.PINNING_TEST: 'https://pinning-test.badssl.com',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.EXPIRED):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        return cls.environments[cls.environment][server]
