
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-19T15:33:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "756ab955e1938e0451ac8d6d7ee90458ff67fd6c",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
