
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-02T12:12:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f5c91e4647a25dce2987a3511f5a4199fc2462e",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
