language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install -y librsvg2-bin

install:
  - python setup.py install

script:
  - pytest
  - cd test; ./test.sh


