binary_sensor:
  - platform: mqtt
    state_topic: ais/button/sensor
    name: ais_remote_button
  - platform: mqtt
    state_topic: ais/button/sensor
    name: selected_entity

sensor:
  - platform: ais_device_search_mqtt
    name: network_devices_info_value
    state_topic: "+/stat/#"

input_text:
  buttons_ais_remote:
    name: Buttons AIS Remote

input_select:
  assistant_voice:
    name: "Głos"
    options:
      - "Jola online"
      - "Jola lokalnie"
      - "Celina"
      - "Anżela"
      - "Asia"
      - "Sebastian"
      - "Bartek"
      - "Andrzej"
    icon: mdi:voice
    initial: "Jola lokalnie"
input_number:
  assistant_rate:
    name: "Szybkość mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1
  assistant_tone:
    name: "Ton mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1

group:
  ais_tts_configuration:
    name: Wybór głosu Asystenta
    control: hidden
    entities:
      - input_select.assistant_voice
      - input_number.assistant_rate
      - input_number.assistant_tone

