################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.org.hibernate.validator.spi.scripting

from jpype.types import *
from typing import Union

from typing import overload

class DefaultScriptEvaluatorFactory:
	def __init__(self, arg0: javawrappers.java.lang.ClassLoader, ): ...
	def getClass(self, ) -> javawrappers.java.lang.Class: ...
	@overload
	def wait(self, arg0: Union[long, JLong], ) -> None: ...
	@overload
	def wait(self, arg0: Union[long, JLong], arg1: Union[int, JInt], ) -> None: ...
	@overload
	def wait(self, ) -> None: ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def notifyAll(self, ) -> None: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def clear(self, ) -> None: ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def getScriptEvaluatorByLanguageName(self, arg0: javawrappers.java.lang.String, ) -> javawrappers.org.hibernate.validator.spi.scripting.ScriptEvaluator: ...
	def notify(self, ) -> None: ...


