[tool.poetry]
name = "barch"
version = "0.1.0"
description = "Tool to support backup and archival"
authors = ["Joachim Hereth <qudade-barch@quda.de>"]

[tool.poetry.dependencies]
python = "^3.7"
click = ">=7.0"
xxhash = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
