# coding: utf-8

"""
    EO Service

    The Enterprise Ontology (EO) aims at establishing a common conceptualization on the Entreprise domain, including organizations, organizational units, people, roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eo_client
from eo_client.models.complex_project_ import ComplexProject_  # noqa: E501
from eo_client.rest import ApiException


class TestComplexProject_(unittest.TestCase):
    """ComplexProject_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplexProject_(self):
        """Test ComplexProject_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eo_client.models.complex_project_.ComplexProject_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
