dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: QeB8md/sKvfkmAV6a53n002sy5Nh5gxCRINCtNpVmL7Gb4OOexJhcKbG/B2mpUDEdPx5PumdC7XGiZsAimSgvoSm/Kf396L8PaGuX2gQKyBbJiK+lrYzkoQTIgADawgnlgrby/gzZkIokhFHvOyeRoFv1h5qIQrx0ax3vT50ZsEtmXLxM6zy2Hw8o4kMnlMu/6ONdTcpmx3PjQmaSyfyCEPaOoThNUcCzZABU6+m3hs8ryUQXrmIGU68r3fGSvfLuPb4zabFt+oLabZ5qhZVOkrDCy1sPI+9GbgHI781YU0SVs88OAB/2tjtGEv8tprcOgkO83J/aU2IogzirvzgleMGpaP0GcOaUHk9IzKwgL82k+8vSk5eg+tw31lFOSBiux2LqJ2wbRRZ7Ei9Y6+EJ0piEI9UCyj25d4zIRsp1dfP8CyVgOQc9YmlHazpyKtUnbd6iFx9ICr5e19Z8LZ4UDgUPQGHFkth7T8B03cvSMu7/hJTka8zB9cCZjaairEwV2Gdwy8k9OwE1YRHvHbRDL9u8tTU57hPiLSpDwuqvf+9FFM1LBkOyrEwamHioD/Qpht5RtSDicnnS3syNURELYtzHyfA1jYcpmtqX5uFQ3qujzTND/vRnvH/pnH97VnuqaijGCpCj/lWr7cZFSwhLN8fRi3LAjxxRedhqviPanA=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_mlx90614.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-mlx90614 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
