# parent job is defined in openstack-manuals
- job:
    name: openstackdocsstheme-tox-manuals-buildpdf
    parent: build-tox-manuals-base
    vars:
      tox_envlist: buildpdf

- job:
    name: openstackdocsstheme-tox-manuals-buildpdf-starlingxpdf
    parent: build-tox-manuals-base
    vars:
      tox_envlist: buildpdf-starlingxdocs

- job:
    name: openstack-tox-docs-starlingxdocs
    parent: openstack-tox-docs
    vars:
      tox_envlist: docs-starlingxdocs

- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstackdocsstheme-tox-manuals-buildpdf
        - openstackdocsstheme-tox-manuals-buildpdf-starlingxpdf
        - openstack-tox-pep8
        - build-openstack-api-ref:
            # Override files section of the job so that this builds
            # if we change the template.
            files:
              - ^tox.ini$
              - ^api-ref/.*
              - ^doc/.*$
              - ^openstackdocstheme/.*$
              - ^.*\.txt$
              - ^.*\.rst$
        # Run the docs build using the starlingxdocs theme
        - openstack-tox-docs-starlingxdocs
    gate:
      jobs:
        - openstackdocsstheme-tox-manuals-buildpdf
        - openstackdocsstheme-tox-manuals-buildpdf-starlingxpdf
        - openstack-tox-pep8
        - build-openstack-api-ref:
            files:
              - ^tox.ini$
              - ^api-ref/.*
              - ^doc/.*$
              - ^openstackdocstheme/.*$
              - ^.*\.txt$
              - ^.*\.rst$
        - openstack-tox-docs-starlingxdocs
    post:
      jobs:
        - publish-openstack-python-branch-tarball
