dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: HL7kVySZDjL21WBlvVB0SYfRIQVgxrzCDbBpu4lfU9uG+S7Cs8rEIIv2n+C4dFC3I7W7X93+8FKno+7TaPqCUw4udapofLoVdh34JhV6/2s7JO7EgshLe8f3jTjGrmkpTq6Beof8Ly+qTm8yvVBamr19g3suya3QBT+Zzci8Hi5SfSlY0QpENpVWNEuL5/G5RdfFdtEeeJZZDnR/RzRRSxLmxOFQ+BqRY3GxRYAxV+KyUHt6op1totWGyIjQYEfr+uTT6cs9nZk6k72/85X4g6ge2ohHGWvdPvCJlW9F8SDY+FMnKzPecOFug7RF6PlE5uJdnRj6iFj/8ts58YeAc6dWiHkVC01pLuMo7bCRHxhO4tXL73+gVwKMjVbZU1K/lJAvVLU14BaMkoXEOCidr0a0qlquxJj1EvZ2qD0msUft1khK9IoFx/v1FCvtjrMnErVzf681W/oiLsO2cL2+/ankGZ4i3cbKaH5Gm8EaJ89NyELTgxMXMi7kMLeb2Gz/yblxl3QzYongDIO4WfoglPjXUHi81Ikas+X7qZlOVsmWnRJ36/MynZ/bN7EVHEb9CItrYbHba9dvZeIEwCB/ctxa9AQM5U1KYUBfhl9gBecrFrghRNm4WpaD4Xvic/JaZReQhnSESm/AqHcmCD1n5joWnmhPRhTLe8+chAUVrqU=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_mcp9808.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-mcp9808 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
