dist: xenial
language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
cache: pip
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U pylint && pylint --rcfile=.pylintrc perfmetrics -f parseable -r n; fi
  - coverage run -p -m zope.testrunner --test-path=src  --auto-color
  - PURE_PYTHON=1 coverage run -p -m zope.testrunner --test-path=src  --auto-color
after_success:
  - coverage combine
  - coverage report
  - coveralls
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
