
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-02T11:02:32-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfdebd87ca79d460aeec106b4bc8643a959ebe9a",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
