
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bc768b336efb69c1b8bc9c49823f22fd4082a638",
 "version": "0.0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
