dist: xenial
language: python

python:
- 3.6
- &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - os: osx
    language: generic
    python: *latest_py3
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - TWINE_USERNAME=__token__
    # TIDELIFT_TOKEN
    - secure: N1YHVPGUZl324ntMUdEUCfuMZb9eTDgEJ5lXQne3WV8bi0DLmoUgDM3z1Hz7RoZY8x8qHLtInNi+8BjqoHwLrbC06A0MZ1aSlqY8pq+nrI6WDQCwFY6BNggl302YiuGdwUtL+W1Yu3SqbFELWMNNM106u+/paZqgt0dP4nE3Qhg=
    - TOX_TESTENV_PASSENV="TWINE_USERNAME TWINE_PASSWORD TIDELIFT_TOKEN"
    script: tox -e release

cache: pip

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis-macos; fi

install:
- pip install tox tox-venv

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: tox
