language: python
cache: pip
dist: xenial

matrix:
  include:
    - name: Lint
      python: 3.7
      env: TOXENV=black,flake8,isort
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox

script:
  - tox
