dist: xenial
group: travis_latest
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    # Lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=manifest

    # Test
    - python: "2.7"
      stage: test
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=py37-oldestAttrs
    - python: "pypy"
      dist: trusty
      env: TOXENV=pypy
    - python: "pypy3"
      dist: trusty
      env: TOXENV=pypy3

    # Docs
    - python: "3.7"
      stage: docs
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=pypi-description


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
