
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-03T12:54:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0bff599fb22c99769bf1a8963579fe59b98b5dac",
 "version": "1.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
