__author__ = 'Managed by Q, Inc.'
__author_email__ = 'open-source@managedbyq.com'
__description__ = 'MBQ Env'
__license__ = 'Apache 2.0'
__title__ = 'mbq.env'
__url__ = 'https://github.com/managedbyq/mbq.env'
__version__ = '2.0.2'
