[tool.poetry]
name = "ezlock"
version = "0.1.3"
description = "Super simple file based locking"
authors = ["0Hughman0 <rammers2@hotmail.co.uk>"]
license = "MIT"
readme = "README.md"
keywords = ["locking", "process", "simple"]
homepage="https://github.com/0Hughman0/ezlock"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
