
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "110e374e1bb26f2802adfd94c9038b0e8b7509bb",
 "version": "0.26.0.b5069"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
