language: python
# sudo: false
dist: xenial

python:
    - '2.7'
    - '3.6'
    - '3.7'

before_install:
    #- TRAVIS_PYTHON_VERSION=`python --version |& awk '{print $2}'|awk -F'.' '{print $1"."$2}'`
    # - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - echo $TRAVIS_PYTHON_VERSION
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - echo $TRAVIS_TAG

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" != "2.7" ]]; then
        conda init bash;
        source $(conda info --root)/etc/profile.d/conda.sh;
      fi
    # - conda create --yes -n travis -c conda-forge python=$TRAVIS_PYTHON_VERSION
    # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    #     source activate travis;
    #   else
    #     conda activate travis;
    #   fi
    - conda install --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION
    - conda install --yes -c conda-forge gcc_linux-64 gxx_linux-64 matplotlib pyyaml scipy numpy h5py setuptools_scm conda-build
    - pwd
    - ./get_nanoversion.sh
    - cat __nanoversion__.txt
    - python setup.py install

script:
    - python setup.py test

deploy:
    # testing pypi
    - provider: pypi
      server: https://test.pypi.org/legacy/
      skip_cleanup: true
      skip_existing: true
      distributions: sdist
      user: atztogo
      password:
        secure: "NDepERc9hinMkLT9r7AqywiZJ7vtxCbrPTJO1abzD4SfW3k+y256XbJNqp/7zQNhi8xplVulOkffAOHXyPTEDiNOBWsF1EE13jSFK6kLjCHTXxZ+mMgO+xHwOaHOTqdZRjsEU4gU28aObVm9/GEl2O5xLWmv5ip6rMDQZTx6enCYdo6OzlTny2WvHIjBSj0FztrWmG7hrgIsjtspyJQk/qBNoOy/fnuQ62PX7pOr9nLlQMEd9XroIzRMbsbA+u9u9KsyONtNRNldJnK542SU36lO0v/aN0fqshIEP9FQWi7KI3L3xtrKqkdj8V4YfDY+s+XeoumuFoNU8GPL2M/Eg3iYGlhwMywKU9U1UrEpKmmVg60Tai/nzpGYQF/2oTH4Zg49mYsiFi7B2oGOhJV545j4zS3g9L4hVGRFzim7PZe5cjNgH+OCVtZxY11KJebygoVn7uTRxAtDq4T2ZFYxqtshzoV7uT/lEUkriXKDIbqJd4x6idH3T5rcdEebJGfnpuBjw+sslG9JIWjl1WMBPbHEhzZNH83YUxqjmg/qJw9BZmuSW7BVxgf+5MN/pBtB8YZMnTQ2tKRI/kTvUutvzABSc0AxdkLlsM7SzCh6WAqdkQb5Sch+FhAaiDupn/gp6CAudVoSWC9WhNsB0oGgHLTmwUKkhg01eniwj40SHII="
      on:
        repo: atztogo/phonopy
        branch: rc
        tags: false
        python: 2.7

    # testing anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh rc $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/phonopy
        branch: rc
        tags: false
        # python: 2.7

    # production pypi
    - provider: pypi
      skip_cleanup: true
      skip_existing: true
      distributions: sdist
      user: atztogo
      password:
        secure: "Jjr207RsWxHXQU0YNjEat/FEk0BsC0ynSP+nYQM0KLWrWzF/NPrutkqdWmvyA/YMZi/ItUMLbHOL9MCPxCeqW8S7vyLXEIs9b5frM2vcNdEDf74W6ZorwusqPIBE9xhdaJVFSFj+SLiU/9OgAbJNMIl6CwIfKRbg5v2lmVKzIe7PqW4HdWYVOkWh8QukGV4rGPtGc6VYjjPuVx7rOkmkOgoF0+roXJZIbAclEcqnIxzYAkiscQaZgCJmagrYKx9RjGC8Y68su4fw1PutQZ9LJElTJ2ZcqVdJa5AOW0ths9qOEXFSuO7ZoTt7nCzEH5N/Abhh3eQ5bRPh+vSpOOUZtfSlDnD6qOf5rBH1w5KyGs3MbDKVJuGr9HQVoMugI9t+/anGyGj2gDAF6r/XRc73aO0cubiV8WZSnHv5Olsq0948hb1Dqz73m09+eIhDnaPDkSHtsoHTPjaBcgMyWpmgVFh9o+fcNQUZzPIeBJfDPowYyjyvLU+H9OkDgnfnOFvSWQfPrHXMdsxSxUX+NKR6U3XuDLYBYctcBg1DR7Nq9i1/W46/HSTmGduboRU/4WDu2jEQ01uTNzlrE8wk9Hwlx7E822iYYv6e1BrACfnmVYoAbIMMk/yo+W33j+HA96Vp7DhUQ95fHBtXZ0ASC5wDbSi1L9vqs4qugSh40dDZeLg="
      on:
        repo: atztogo/phonopy
        branch: master
        tags: false
        python: 2.7

    # production anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh main $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/phonopy
        branch: master
        tags: false
        # python: 2.7
