[tool.poetry]
name = "incidental"
version = "0.0.1"
description = ""
authors = ["cloudcraeft <cloudcraeft@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
invoke = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
