[tool.poetry]
name = "statsapiclient"
version = "0.0.1"
description = ""
homepage="https://github.com/hockeymonkeys/statsapiclient"
repository="https://github.com/hockeymonkeys/statsapiclient"
documentation="https://github.com/hockeymonkeys/statsapiclient#README.rst"
license="MPL-2.0"
authors = ["Brett LaBombarda <bplabombarda@gmail.com>"]
readme = "README.rst"
keywords = ["nhl", "hockey"]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "^1.0"
jupyterthemes = "^0.20.0"
requests = "^2.21"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pdoc3 = "^0.6.3"
pylint = "^2.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
