[tool.poetry]
name = "dophon_cloud"
version = "1.0.3"
description = "dophon cloud(import reg center)"
authors = ["CallMeE <ealohu@163.com>"]
license = "Apache 2.0"
url='https://github.com/Ca11MeE/dophon_cloud'

[tool.poetry.dependencies]
dophon = "*"
dophon_cloud_center = "*"
py_eureka_client = "*"

[tool.poetry.dev-dependencies]
dophon = "*"
dophon_cloud_center = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
