language: python
python: 3.7
dist: xenial
env:
  global:
    - DRF="djangorestframework==3.10.2"
    - DJANGO="django==2.2.4"
    - WQIO="wq.io==1.1.0"
matrix:
  include:
    - name: "Defaults (Python 3.7, Django 2.2, DRF 3.10)"
    - name: "+ immediate"
      env:
        - NOTHREADING="1"
    - name: "+ celery"
      env:
        - CELERY="celery==4.3.0"
        - REDIS="redis"
    - name: "+ wq.db"
      env:
        - WQDB="git+https://github.com/wq/wq.db.git#egg=wq.db"
    - name: "+ wq.db + reversion"
      env:
        - WQDB="git+https://github.com/wq/wq.db.git#egg=wq.db"
        - REVERSION="django-reversion"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.5"
      python: "3.5"
    - name: "Django 2.1"
      env:
        - DJANGO="django==2.1.11"
    - name: "Django 1.11"
      env:
        - DJANGO="django==1.11.23"
    - name: "DRF 3.9"
      env:
        - DRF="djangorestframework==3.9.4"
    - name: "Python 3.4, Django 1.11, DRF 3.9"
      python: "3.4"
      env:
        - DJANGO="django==1.11.23"
        - DRF="djangorestframework==3.9.4"
    - name: "Python 2.7, Django 1.11, DRF 3.9"
      python: "2.7"
      env:
        - DJANGO="django==1.11.23"
        - DRF="djangorestframework==3.9.4"
    - name: "Python 2.7, Django 1.8, DRF 3.6 + celery"
      python: "2.7"
      env:
        - DJANGO="django==1.8.19"
        - DRF="djangorestframework==3.6.4"
        - CELERY="celery==4.2.1"
        - REDIS="redis"
    - name: "Code Lint"
      env:
        - LINT="flake8"
install:
 - pip install $DJANGO $CELERY $REDIS $DRF $WQIO $WQDB $REVERSION $LINT
 - pip install .
script:
 - ./runtests.sh
services:
 - redis-server
