[tool.poetry]
name = "ezlock"
version = "0.1.0"
description = ""
authors = ["0Hughman0 <rammers2@hotmail.co.uk>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
