# coding: utf-8

"""
    EO Service

    The Enterprise Ontology (EO) aims at establishing a common conceptualization on the Entreprise domain, including organizations, organizational units, people, roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eo_client
from eo_client.api.atomic_projects_api import AtomicProjectsApi  # noqa: E501
from eo_client.rest import ApiException


class TestAtomicProjectsApi(unittest.TestCase):
    """AtomicProjectsApi unit test stubs"""

    def setUp(self):
        self.api = eo_client.api.atomic_projects_api.AtomicProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_atomic_projects_create(self):
        """Test case for atomic_projects_create

        """
        pass

    def test_atomic_projects_delete(self):
        """Test case for atomic_projects_delete

        """
        pass

    def test_atomic_projects_list(self):
        """Test case for atomic_projects_list

        """
        pass

    def test_atomic_projects_partial_update(self):
        """Test case for atomic_projects_partial_update

        """
        pass

    def test_atomic_projects_read(self):
        """Test case for atomic_projects_read

        """
        pass

    def test_atomic_projects_update(self):
        """Test case for atomic_projects_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
