[tool.poetry]
name = "torchtrainer"
version = "0.3.8"
description = "Focus on building and optimizing pytorch models not on training loops"
authors = ["Victor Künstler <victor.kuenstler@outlook.com>"]
readme = "README.md"
homepage = "https://github.com/VictorKuenstler/torchtrainer"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
torch = "^1.2"
torchvision = "^0.4.0"
visdom = "^0.1.8"
tqdm = "^4.33"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
pycodestyle = "^2.5"
pytest-cov = "^2.7"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
