################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import javawrappers.java.lang
import javawrappers.org.hibernate.validator.constraints.pl

from jpype.types import *
from typing import Union

from typing import overload

class NIP:
	class List:
		def hashCode(self, ) -> Union[int, JInt]: ...
		def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def annotationType(self, ) -> javawrappers.java.lang.Class: ...
		def toString(self, ) -> javawrappers.java.lang.String: ...
		def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.NIP, 1): ...


	def payload(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def annotationType(self, ) -> javawrappers.java.lang.Class: ...
	def groups(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def message(self, ) -> javawrappers.java.lang.String: ...
	def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.NIP, 1): ...


class PESEL:
	class List:
		def hashCode(self, ) -> Union[int, JInt]: ...
		def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def annotationType(self, ) -> javawrappers.java.lang.Class: ...
		def toString(self, ) -> javawrappers.java.lang.String: ...
		def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.PESEL, 1): ...


	def payload(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def annotationType(self, ) -> javawrappers.java.lang.Class: ...
	def groups(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def message(self, ) -> javawrappers.java.lang.String: ...
	def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.PESEL, 1): ...


class REGON:
	class List:
		def hashCode(self, ) -> Union[int, JInt]: ...
		def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
		def annotationType(self, ) -> javawrappers.java.lang.Class: ...
		def toString(self, ) -> javawrappers.java.lang.String: ...
		def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.REGON, 1): ...


	def payload(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def hashCode(self, ) -> Union[int, JInt]: ...
	def equals(self, arg0: javawrappers.java.lang.Object, ) -> Union[int, JBoolean]: ...
	def annotationType(self, ) -> javawrappers.java.lang.Class: ...
	def groups(self, ) -> JArray(javawrappers.java.lang.Class, 1): ...
	def toString(self, ) -> javawrappers.java.lang.String: ...
	def message(self, ) -> javawrappers.java.lang.String: ...
	def value(self, ) -> JArray(javawrappers.org.hibernate.validator.constraints.pl.REGON, 1): ...


