[tool.poetry]
name = "s3pypi"
version = "0.9.1"
description = "CLI for creating a Python Package Repository in an S3 bucket"
authors = [
    "Matteo De Wint <matteo@novemberfive.co>",
    "Ruben Van den Bossche <ruben@novemberfive.co>",
]

[tool.poetry.scripts]
s3pypi = "s3pypi.__main__:main"

[tool.poetry.dependencies]
boto3 = "^1.9.211"
Jinja2 = "^2.10.1"
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0", allows-prereleases = true}
flake8 = "^3.7.8"
isort = "^4.3.21"
moto = "^1.3.13"
pytest = "^5.1.0"
pytest-cov = "^2.7.1"

[tool.black]
exclude = '''
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
