
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-31T17:49:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d2e8a97f6d8e27d9aa6d9fdd37a4ff44bc334f5",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
