[tool.poetry]
name = "strong-aws-lambda.contract"
version = "0.1.0"
description = "Create static type event"
authors = ["Rodrigo Farias Rezino <rodrigofrezino@gmail.com>"]
license = "MIT"
readme = "README.md"

packages = [
    {include="strong_aws_lambda_contract_pkg", from="."}
]

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry.dependencies]
python = "^3.7"
dacite = "^1.0"
aws-lambda-context = "^1.1"

[tool.poetry.dev-dependencies]
mock = "^3.0"
pytest = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.extras]
test = ["coverage"]

[tool.poetry.virtualenvs]
venv3 = { python = "^3.7" }
