
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-19T10:32:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a222ac882aa1e46c30ec01d8f3f4a746863712d",
 "version": "0.3b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
