[tool.poetry]
name = "red-connector-xnat"
version = "1.0"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-xnat"
homepage = "https://www.curious-containers.cc/"
description = "RED Connector XNAT is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
requests = "^2.18"
jsonschema = "^3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-xnat-http = 'red_connector_xnat.main:main'
